### ISSUE TITLE
Cant find useNavigationState

### ISSUE THREAD

**Issue by lucasluca** [react-navigation/react-navigation-4#6617]
**Current Behavior**

- Im using react navigation v5 Aplha and i try to import the hook useNavigationState, but it could not find it
- Include a screenshot or video if it makes sense.

**Expected Behavior**

-
![image](https://user-images.githubusercontent.com/16627838/72990510-08008d80-3dcf-11ea-9e42-9da34bcbba0a.png)

**How to reproduce**

-just installed react navigation v5 dependencies and can not get useNavigationState

**Comment by fabiobends** [comment]
If you ever run into this issue, the following tweak in your `tsconfig.json` might fix it (worked for me):

```jsonc
  // ...
  "module": "es2020",
  "target": "es2020",
  "moduleResolution": "bundler",
  // ...
```
