### ISSUE TITLE
How to prevent AppBar  header to animate on view change on Android?

### ISSUE THREAD

**Issue by kopax** [react-navigation/react-navigation-4#6619]
**Current Behavior**

I am using `@react-navigation/stack@5.0.0-alpha.53` and I use the `TransitionPresets.SlideFromRightIOS`.

When the next view comes in, it also brings the `<AppBar />` header with animation, making it slide on top of the initial header.

Is there a way to prevent that glitch and disable animation on the `<AppBar />`?

**Expected Behavior**

I expect the AppBar to be fixed

**How to reproduce**

```jsx
import * as React from 'react';
import { createStackNavigator as createStackNavigatorDefault, TransitionPresets } from '@react-navigation/stack';
import Constants from 'expo-constants';
import { getStackConfig } from './utils';

export default function createStackNavigator(routes) {
  const REACT_PAPER_APPBAR_HEIGHT = 56;
  const Stack = createStackNavigatorDefault();
  // eslint-disable-next-line react/prop-types
  return ({ screenOptions }) => (
    <Stack.Navigator
      {...getStackConfig(routes)}
      screenOptions={{
        headerStyle: {
          height: Constants.statusBarHeight + REACT_PAPER_APPBAR_HEIGHT,
        },
        ...TransitionPresets.SlideFromRightIOS,
        ...screenOptions,
      }}
    >
      {routes.map((route) => (
        <Stack.Screen
          key={route.path}
          name={route.page}
          component={route.component}
          options={{ title: route.message }}
        />
      ))}
    </Stack.Navigator>
  );
}
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/stack         | 5.0.0-alpha.53
| expo                           | sdk36
| node                           | v13.5.0
| npm                     | 6.13.4

**Comment by newyorksoul** [comment]
I would have liked this for views with the same title. Same headers don't need animation just the body

**Comment by amin79** [comment]
@kopax did you find any solution?
