### ISSUE TITLE
[v5] Some thoughts on onFocusEffect API

### ISSUE THREAD

**Issue by lachenmayer** [react-navigation/react-navigation-4#6622]
Hi there, I've converted our app to react-navigation v5, and so far it's been a real breeze - loving the new API, especially being able to type-check `navigate` calls, great job!

One thing that was a bit confusing initially is how `onFocusEffect` works - this isn't necessarily a bug, but I thought it'd be useful to give this feedback now, before the API is totally stable. Feel free to ignore if you're set on the current API :)

TL;DR:

- You currently need to return `undefined` in the `onFocusEffect` callback if you don't want to return a cleanup function.
- `useFocusEffect` triggers on every render if focused, it would be nice if you could control this without having to use `React.useCallback`

## Current Behavior

In our code using react-navigation v4, we have the following pattern in a couple of places:

```ts
const { data, refetch } = useQuery(...)
navigation.addListener('willFocus', () => refetch())
```

In v5, I initially replaced this with the following:

```ts
const { data, refetch } = useQuery(...)
useFocusEffect(() => {
  refetch()
  return undefined // this is required, see below!
})
```

The [`useFocusEffect` docs](https://reactnavigation.org/docs/en/next/use-focus-effect.html) say:

> The `useFocusEffect` is analogous to React's `useEffect` hook. The only difference is that it runs on focus instead of render.

Now, what I expected "runs on focus instead of on render" to mean is that `refetch` would be called (once) when the screen is focused. Instead, that screen kept flickering between the loading state and the loaded state.

---

Separately, I had to add `return undefined` to the `useFocusEffect` callback because it has the following type:

```ts
// from react-navigation
type EffectCallback = (() => undefined) | (() => () => void);
```

I believe it would be better to use the `EffectCallback` definition that ships with React's TypeScript definition:

```ts
// from @types/react
type EffectCallback = () => (void | (() => void | undefined));
```

This would allow removing the unnecessary return statement. This one should be an easy fix :)

## Expected Behavior

Properly re-reading the docs, I found that this is actually the expected behavior, ie. the callback gets triggered every time the component re-renders while focused. The docs suggest to use `React.useCallback` to control how often the callback should be triggered. Changing the call to the following did indeed work as expected:

```ts
useFocusEffect(
  React.useCallback(() => {
    refetch()
    return undefined
  }, [])
)
```

I feel like that's a lot of code for something as simple as "refetch every time the screen is focused". 

In our codebase, I count over 50 uses of React's built-in `useEffect` hook, and every single one of those calls uses the array argument, because we always want to either (a) perform an effect on component mount (ie. as a replacement to `componentDidMount`), or (b) whenever some value changes (ie. as a replacement to `componentDidUpdate`). As such, I found it quite weird that you have to add `React.useCallback` to get that same behavior using `useFocusEffect`.

## Proposed changes

I propose changing `useFocusEffect` to add the array of dependencies as an optional second argument, so that all of the following are valid:

```ts
// This should refetch once the screen is focused.
useFocusEffect(() => {
  refetch()
}, [])

// This should subscribe once the screen is focused, and unsubscribe once the screen is unfocused.
useFocusEffect(() => {
  subscribe()
  return () => unsubscribe()
}, [])

// Same behavior as before, ie: run on every render while focused.
useFocusEffect(() => {
  doSomething()
})
```

This would make `useFocusEffect` work exactly like `useEffect`, except that it only runs when the screen is focused, as advertised :)

## How to reproduce

(I hope this doesn't need a repro, let me know if you'd like one!)

## Your Environment

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both |
| @react-navigation/native       | 5.0.0-alpha.27 |
| react-native                   | whatever Expo 36 ships with |
| expo                           | 36.0.1 |
| node                           | 12 |
| npm or yarn                    | npm |

**Comment by aldegoeij** [comment]
@lachenmayer appreciate you filing this issue! 

It has helped me figure out what I was doing wrong in trying to use `useFocusEffect` in combination with `useLazyQuery` (Apollo obv), to refresh a `FlatList` when navigating back to a screen, which is causing a cache miss (https://github.com/apollographql/react-apollo/issues/3655)

Totally missed the `refetch` on `useQuery`🤦

**Comment by aldegoeij** [comment]
For those finding this discussion, `refetch` is broken on React Native when there is a network error: https://github.com/apollographql/react-apollo/issues/2070.

For those as desperate as me: I just wanted a screen with a flatlist that would render from cache on network error and recover when network returned. 

I managed to do this with a `useQuery` with `fetchPolicy` on `cache-only` and a `useLazyQuery` with regular `cache-and-network` `fetchPolicy` (with exactly the same query variables) to use in `onRefresh`. 
The flatlist depends on the data element from the `useQuery`, which automagically gets updated by the `useLazyQuery` when a user or a `useFocusEffect` triggers it.

**Comment by florian-milky** [comment]
I agree with @lachenmayer I was also confused by `useFocusEffect` running on renders

**Comment by flashjames** [comment]
I agree with @florian-milky  and @lachenmayer 

I ended up writing this effect:

```
/*
  Reasoning behind this Effect
  https://github.com/react-navigation/react-navigation/issues/6622

  useFocusEffect is called on every render, but I want the callback to only be
  called once on coming to the component.

  => useRealIsFocusedEffect
 */

export const useRealIsFocusedEffect = (callback) => {
  const isFocused = useIsFocused();
  useFocusEffect(
    React.useCallback(() => {
      if(!isFocused) return
      callback()
    }, [isFocused])
  )
}

```

**Comment by AndreasGalster2** [comment]
This is a bit of an old one, but I figured somebody might run into this. I struggled a lot with refetching on React Native/Expo and useQuery... useFocusEffect would always hard-trigger refetches during HMR.

```
  useFocusEffect(
    React.useCallback(() => {
      // console.log('refetching')
      logger.info("🚀 Refetching");
        refetch();
      return () => {};
    }, [])
  );

  const { loading, error, data, refetch } = useQuery(GET_ALL_BUT_CLOSED_RACES, {
    variables: { limit: 20, offset: 0 },
    notifyOnNetworkStatusChange: true
  });
```

e. g. this would re-trigger the **Query**, not just trigger a re-fetch. So on every small change on the screen, it would call my APIs. I tried above suggestion and many others, but found that useFocusEffect would always re-trigger the useQuery.

The solution I found is this:


```
  const { loading, error, data, refetch } = useQuery(GET_ALL_BUT_CLOSED_RACES, {
    variables: { limit: 20, offset: 0 },
    notifyOnNetworkStatusChange: true
  });

  useFirstFocus(() => {
    logger.info('🚀Screen focused for first time or refocused after navigation');
    refetch();
  });
```

I built my own hook, inspired by isFirstRender from useHooks, which uses isFocused rather than useFocusEffect. I have to validate this for a while to make sure it works reliably, but it seems good to me so far. 

Effectively, what the hook does is determine whether we are on the focused screen, if yes, only runs the callback once, and ignores hot module reloads that tend to get triggered via useFocusEffect.

PS: Used Sonnet 3.7 to write the hook, in case of copyright concerns.

```
import { useRef, useCallback,useEffect } from 'react';
import { useFocusEffect, useIsFocused } from '@react-navigation/native';

/**
 * Custom hook that runs effects only when a screen is focused for the first time
 * or when it regains focus after being unfocused
 */
export function useFirstFocusEffect(callback) {
  // Track if the screen is focused
  const isFocusedRef = useRef(false);
  
  // Track if we should run effects when focusing
  const shouldRunEffectsRef = useRef(true);

  useFocusEffect(
    useCallback(() => {
      // When gaining focus, run the callback if needed
      if (shouldRunEffectsRef.current) {
        callback();
        shouldRunEffectsRef.current = false;
      }
      
      isFocusedRef.current = true;
      
      // Return cleanup function that runs when losing focus
      return () => {
        isFocusedRef.current = false;
        // Reset the flag when we lose focus
        shouldRunEffectsRef.current = true;
      };
    }, [callback])
  );
}


/**
 * Custom hook that detects first focus and refocus events without
 * causing unnecessary re-renders during HMR
 * 
 * @param callback Function to call when screen is first focused or refocused
 */
export function useFirstFocus(callback) {
  const isFocused = useIsFocused();
  const wasFocusedRef = useRef(false);
  const didRunForCurrentFocusRef = useRef(false);
  
  useEffect(() => {
    // Only run if we are focused now and either:
    // 1. We weren't focused before (first time or returning to screen)
    // 2. We haven't run the callback for the current focus session
    if (isFocused && (!wasFocusedRef.current || !didRunForCurrentFocusRef.current)) {
      callback();
      wasFocusedRef.current = true;
      didRunForCurrentFocusRef.current = true;
    }
    
    // If we lose focus, reset the "did run" flag but keep track that we were focused before
    if (!isFocused && wasFocusedRef.current) {
      didRunForCurrentFocusRef.current = false;
    }
  }, [isFocused, callback]);
}
```
