### ISSUE TITLE
Swiping between tabs on TextInput does not work for MaterialTopTabNavigator on Android

### ISSUE THREAD

**Issue by Lerosen** [react-navigation/react-navigation-4#6624]
**Current Behavior**
I'm using the MaterialTopTabNavigator and one tab contains a TextInput. On Android, trying to switch tabs by swiping from this tab does not work.

**Expected Behavior**
I expect swiping between tabs with a TextInput to also work on Android.

**How to reproduce**
see
https://snack.expo.io/@lerosen/tab-navigation-%C2%B7-react-navigation
swiping to the settings tab works as expected but swiping back to does not (on Android).

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | Android
| @react-navigation/native            | ^5.0.0-alpha.18
| @react-navigation/material-top-tabs | ^5.0.0-alpha.22
| react-native-tab-view               | ^2.11.0
| react-native                        | 62.0.0
| expo                                | 36.0.0
| node                                |
| npm or yarn                         |

**Comment by pedrobneto** [comment]
Hello, I'm having the same problem with MaterialTopTabNavigator 5.3.6, the swipe action doesn't work at all when swiping on top of TextInput, can you explain how you fixed it?
