### ISSUE TITLE
Upgrading from version 4 to 5: White background flashing when switching screens

### ISSUE THREAD

**Issue by janoist1** [react-navigation/react-navigation-4#6626]
I'm migrating a RN project version 4 to 5.

When switching screens there's an issue with a white background flashing in.
In v4 this was solved by setting `cardStyle: { backgroundColor: material.containerBgColor }` in the `StackNavigation` options.

However in v5 I'm unable to fix it with the same approach:

`<Stack.Navigator screenOptions={{ cardStyle: { backgroundColor: material.containerBgColor } }} ...>`

White flash has come back. Any idea how to fix it? The docs don't tell too much about the `ScreenOptions` object, or is this me not being able to find it?

The structure of the navigation may be important:

```
const AppTabNavigator = () => (
  <Tab.Navigator>
    <Tab.Screen name="Home" component={Home} />
    <Stack.Screen name="ScreenD" component={ScreenD} />
    <Stack.Screen name="ScreenE" component={ScreenE} />
    <Stack.Screen name="ScreenF" component={ScreenF} />
  </Tab.Navigator>
)
...
  <Stack.Navigator
    screenOptions={{ cardStyle: { backgroundColor: material.containerBgColor } }}
  >
    <Stack.Screen name="Home" component={AppTabNavigator} />
    <Stack.Screen name="ScreenA" component={ScreenA} />
    <Stack.Screen name="ScreenB" component={ScreenB} />
    <Stack.Screen name="ScreenC" component={ScreenC} />
  </Stack.Navigator>
```

Going from ScreenD to ScreenE does the flashing issue. I'm not sure about the other screens as they don't make any network request / async stuff.

**Comment by pustylnikov** [comment]
Just wrap your navigator in `View` component, and set `backgroundColor`. I usually set a color like the background color of the header.

For example: 
```
const MyStackNavigator = () => (
  <View style={{ backgroundColor: '#000' }}>
    <Stack.Navigator>
      <Stack.Screen name="ScreenA" component={ScreenA} />
      <Stack.Screen name="ScreenB" component={ScreenB} />
      <Stack.Screen name="ScreenC" component={ScreenC} />
    </Stack.Navigator>
  </View>
)
```

**Comment by Matchdev120** [comment]
This works for me.

`sceneContainerStyle={{ backgroundColor: 'rgba(0, 0, 0, 0)' }}`
