### ISSUE TITLE
Why you have been deleted lot of issues?

### ISSUE THREAD

**Issue by vargajacint** [react-navigation/react-navigation-4#6633]
**A last couple day a lot of issues gone.**

For example:
https://github.com/react-navigation/react-navigation/issues/5677
https://github.com/react-navigation/react-navigation/issues/739
https://github.com/react-navigation/react-navigation/issues/2631
https://github.com/react-navigation/react-navigation/issues/5965
https://github.com/react-navigation/react-navigation/issues/581

I'm looking for answer, when i hide the tab bar and i show again why i get frame drop (laggy)?

**Comment by EmpireJones** [comment]
It looks like they were moved back again
