### ISSUE TITLE
Creating a navigator don't make take an argument.May be you are trying to use React Navigation 4 Api with react navigation 5..

### ISSUE THREAD

**Issue by 2016CS112** [react-navigation/react-navigation-4#6637]

**Comment by MZabih** [comment]
![Simulator Screen Shot - iPhone 8 Plus - 2020-02-12 at 11 32 51](https://user-images.githubusercontent.com/24524961/74308972-6c3dbe00-4d8b-11ea-9881-37636d49b232.png)

This is the error I am seeing, however i am using 
```"@react-native-community/masked-view": "^0.1.6",
    "@react-navigation/native": "^5.0.2",
    "@react-navigation/stack": "^5.0.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.6",
    "react-native-safe-area-context": "^0.7.2",
    "react-native-screens": "^2.0.0-beta.2",
    "react-navigation": "^4.1.1"
```
Please suggest where i am doing mistake. 
Thanks in advance

**Comment by MZabih** [comment]
I have resolved this issue by replacing `@react-navigation/stack` with `react-navigation-stack`

**Comment by support999** [comment]
"dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/stack": "^5.6.0",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^3.0.6",
    "react-native-screens": "^2.9.0"
  },
I am also having the same problem , please help me to solve it .

**Comment by artr-vnk** [comment]
Hello, dear programmers!
I had the same problem and I resolved it. And now I wanna give you my code. I hope my code helps you!

npm install react-navigation@^4.1.1

expo install react-native-gesture-handler react-native-reanimated react-native-screens react-native-safe-area-context 
@react-native-community/masked-view

npm install react-navigation-stack

 "dependencies": {
    "@react-native-community/masked-view": "0.1.10",
    "expo": "~38.0.1",
    "expo-font": "^8.2.1",
    "expo-status-bar": "^1.0.0",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.9.0",
    "react-native-safe-area-context": "3.0.2",
    "react-native-screens": "~2.9.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.1.1",
    "react-navigation-stack": "^2.8.2"
  },

**Comment by Madiha86** [comment]
same issue i have faced .....please suggest me

**Comment by anuragipankaj** [comment]
SAME ISSUE HERE :(

**Comment by vinaciotm** [comment]
instead of :
```
const HomeTabs = createBottomTabNavigator({
  Day: DayScreen,
  Days: DaysScreen,
});
```

use this:
```
const HomeTabs = createBottomTabNavigator();
const Home = () => (
  <HomeTabs.Navigator>
    <HomeTabs.Screen name="Day" component={DayScreen} />
    <HomeTabs.Screen name="Days" component={DaysScreen} />
  </HomeTabs.Navigator>
);
```
