### ISSUE TITLE
 Couldn't register the navigator. Have you wrapped your app with 'NavigationContainer'?  app is crashing

### ISSUE THREAD

**Issue by ilibilibom** [react-navigation/react-navigation-4#6645]
HI 
I'm trying to implement the react-navigation native stack navigator with the material bottom tab navigator. 
I'm using v5 of react-navigation, and gone through the installation process here:
https://reactnavigation.org/docs/en/next/native-stack-navigator.html   

I'm getting the error: 
```Error: Couldn't register the navigator. Have you wrapped your app with 'NavigationContainer’?```
and then the app crashes. 

I'm wrapping the tab navigator with: 
``` <NavigationNativeContainer>```

here is my code:
```
const Stack = createNativeStackNavigator();

function homeStack() {
  return (
    <Stack.Navigator>
      <Stack.Screen
        name="Home"
        component={Home}
        options={{
          header: null,
        }}
      />
      <Stack.Screen
        name="Item"
        component={Item}
        options={{
          title: '',
          // tabBarVisible: false,
        }}
      />
    </Stack.Navigator>
  );
}
```
and the material tab navigator:
```
const Tab = createMaterialBottomTabNavigator();

const StackTabs = function StackTabs({theme}: Props) {
  return (
    <NavigationNativeContainer>
      <StatusBar
        backgroundColor={theme.colors.primary}
        barStyle="light-content"
      />
      <Tab.Navigator
        initialRouteName="Home"
        activeColor={theme.colors.primary}
        shifting={false}
        barStyle={{backgroundColor: '#fff'}}>
        <Tab.Screen
          name="Home"
          component={homeStack}
          options={{
            tabBarLabel: 'Home',
            tabBarIcon: ({color}) => (
              <Icon name="home" color={color} size={25} />
            ),
          }}
        />

      </Tab.Navigator>

    </NavigationNativeContainer>
  );
};
```
Any idea why is this happening

**Comment by ambessh** [comment]
import { NavigationContainer } from '@react-navigation/native';
<NavigationContainer>WRAP YOUR STACK NAVIGATOR</NavigationContainer>

**Comment by Darpsoft** [comment]
Try with

```
const StackTabs = function StackTabs({theme}: Props) {
  ...
}

const Navigation = (props) => {
  return(
    <NavigationContainer>
      <StackTabs props={props}/>
    </NavigationContainer>
  )
}

export default Navigation
```

**Comment by RonanCastro** [comment]
i have same insue with example code.

Erro: Couldn´t register the navigator. Have you warpped your app with 'NavigationContainer'?

App.js
`import * as React from 'react';
import { View, Text } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createDrawerNavigator } from '@react-navigation/drawer';

function Feed() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Feed Screen</Text>
    </View>
  );
}

function Article() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Article Screen</Text>
    </View>
  );
}

const Drawer = createDrawerNavigator();

function MyDrawer() {
  return (
    <Drawer.Navigator>
      <Drawer.Screen name="Feed" component={Feed} />
      <Drawer.Screen name="Article" component={Article} />
    </Drawer.Navigator>
  );
}

export default function Menu() {
  return (
    <NavigationContainer>
      <MyDrawer />
    </NavigationContainer>
  );
}`
package.json
`{
  "name": "exercicios",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/drawer": "^5.5.1",
    "@react-navigation/native": "^5.1.7",
    "@react-navigation/stack": "^5.2.14",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.7.0"
  },
  "devDependencies": {
    "@babel/core": "7.9.0",
    "@babel/runtime": "7.9.2",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.8.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.58.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

**Comment by devhribeiro** [comment]
> NavigationContainer

correta a resposta!

**Comment by CharlotteRdn** [comment]
I have the same issue... I don't understand why... 

```
import React from 'react';
import { Image } from 'react-native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { createStackNavigator} from "@react-navigation/stack";
import { NavigationContainer, useNavigation } from '@react-navigation/native';
import Authentication from '../../Screens/Authentication';
import Activities from '../../Screens/Activities';
import Login from '../../Screens/Authentication/Login';
import Register from '../../Screens/Authentication/Register';
import Tools from '../../Screens/Tools';
import Dashboard from '../../Screens/Dashboard';
import Orders from '../../Screens/Orders';
import Completed from '../../Screens/Orders/Completed';
import Current from '../../Screens/Orders/Current';
import Details from '../../Screens/Orders/Details';
import Settings from '../../Screens/Settings';
import Scan from '../../Screens/Tools/Scan';
import Products from '../../Screens/Tools/Products';
import Tickets from '../../Screens/Tools/Tickets';
import Welcome from '../../Screens/Welcome';
import i18n from '../../src/i18n';
import styles from '../../assets/styles';

const Tab = createBottomTabNavigator();
const Stack = createStackNavigator();

export default function ScreenNavigator() {
  return(
    <NavigationContainer>
      <Stack.Navigator>       
        <Stack.Screen name = 'Orders' component = {Orders} options={{ title: i18n.t("orders.title") }}/> 
        <Stack.Screen name = 'Authentication' component = {Authentication} options={{ title: i18n.t("authentication.title") }}/>  
        <Stack.Screen name = 'Activities' component = {Activities} options={{ title: i18n.t("activities.title") }}/>  
        <Stack.Screen name = 'Login' component = {Login} options={{ title: i18n.t("login.title") }}/>
        <Stack.Screen name = 'Register' component = {Register} options={{ title: i18n.t("register.title") }}/>
        <Stack.Screen name = 'Tools' component = {Tools} options={{ title: i18n.t("tools.title") }}/>
        <Stack.Screen name = 'Scan' component = {Scan} options={{ title: i18n.t("scan.title") }}/>      
        <Stack.Screen name = 'Current' component = {Current} options={{ title: i18n.t("current.title") }}/>
        <Stack.Screen name = 'Completed' component = {Completed} options={{ title: i18n.t("completed.title") }}/>
        <Stack.Screen name = 'Details' component = {Details} options={{ title: i18n.t("details.title") }}/> 
        <Stack.Screen name = 'Products' component = {Products} options={{ title: i18n.t("products.title") }}/>      
        <Stack.Screen name = 'Tickets' component = {Tickets} options={{ title: i18n.t("tickets.title") }}/>
        <Stack.Screen name = 'Dashboard' component = {Dashboard} options={{ title: i18n.t("dashboard.title") }}/>
        <Stack.Screen name = 'Settings' component = {Settings} options={{ title: i18n.t("settings.title") }}/>
        <Stack.Screen name = 'Welcome' component = {Welcome} options={{ title: i18n.t("welcome.title") }}/>
      </Stack.Navigator>
    </NavigationContainer>
  )
}

 export function AppNavigation() {
  return (    
      <Tab.Navigator tabBarOptions={{activeTintColor: 'black',
                     labelStyle: {fontSize: 12, color: 'white'}, 
                     style: {backgroundColor: '#F78400'},
                     }}>
        <Tab.Screen
          name={i18n.t("orders.title")}
          component={ScreenNavigator}
          options={{
              tabBarIcon: ({ focused, horizontal, tintColor }) => {
                return (
                  <Image
                    source={require("../../assets/images/orders.png")}
                    style={styles.icon}
                  />
                );
              }
          }}
        />
        <Tab.Screen
          name={i18n.t("dashboard.title")}
          component={Dashboard}
          options={{
            tabBarIcon: ({ focused, horizontal, tintColor }) => {
              return (
                <Image
                  source={require("../../assets/images/dashboard.png")}
                  style={styles.icon}
                />
              );
            }
          }}
        />
        <Tab.Screen
          name={i18n.t("tools.title")}
          component={Tools}
          options={{
            tabBarIcon: ({ focused, horizontal, tintColor }) => {
              return (
                <Image
                  source={require("../../assets/images/tools.png")}
                  style={styles.icon}
                />
              );
            }
          }}
        />
        <Tab.Screen
          name={i18n.t("settings.title")}
          component={Settings}
          options={{
            tabBarIcon: ({ focused, horizontal, tintColor }) => {
              return (
                <Image
                  source={require("../../assets/images/settings.png")}
                  style={styles.icon}
                />
              );
            }
          }}
        />
      </Tab.Navigator>
    
  )
}
```

**Comment by chj-damon** [comment]
I'm trying to upgrade `react-navigation-shared-element` to match v6, I encountered the same error But I can confirm that I do wrap my Stack under `NavigationContainer`.

App.tsx:
```tsx
export default () => {
  return (
  <NavigationContainer>
    <SimpleStack />
  </NavigationContainer>
);
}
```
SimpleStack.tsx
```tsx
import {createSharedElementStackNavigator} from 'react-navigation-shared-element';

import {MasterScreen, DetailScreen, createScreen} from '../screens';

const name = 'SimpleStack';

const Stack = createSharedElementStackNavigator({
  name,
  debug: true,
});

const Detail1Screen = createScreen(DetailScreen, undefined, undefined, {
  onPress: ({navigation, item}: any) => {
    navigation.push('Detail2', {
      item,
    });
  },
});

const Detail2Screen = createScreen(DetailScreen, undefined, undefined, {
  resizeMode: 'contain',
});
Detail2Screen.displayName = 'Detail2Screen';

export default () => (
  <Stack.Navigator>
    <Stack.Screen name={name} component={MasterScreen} />
    <Stack.Screen name="Detail" component={Detail1Screen} />
    <Stack.Screen name="Detail2" component={Detail2Screen} />
  </Stack.Navigator>
);
```
I don't know why it's not working. the `createSharedElementStackNavigator` is pretty much the same like `createStackNavigator`

**Comment by emekaokoli** [comment]
any fix on this?

**Comment by vinaysharma14** [comment]
If you're using a **mono-repo** architecture like **yarn workspaces**, chances are that you have multiple versions of `@react-navigation/native` present in different package.json files you have. This would result in a conflict and would cause unintended behavior.

So, I was able to fix it by ensuring that the same package version is present across 2 different package.json files my project uses. Moreover, you should also check out other dependencies as well `@react-navigation/stack` in the same manner.

**Comment by vinaysharma14** [comment]
If you're using a **mono-repo** architecture like **yarn workspaces**, chances are that you have multiple versions of `@react-navigation/native` present in different package.json files in your project. This would result in a conflict and would cause unintended behavior.

So, I was able to fix it by ensuring that the same package version is present across 2 different package.json files my project uses. Moreover, you should also check out other dependencies as well `@react-navigation/stack` in the same manner.

**Comment by yungpear** [comment]
> @react-navigation/native

Thank you - this is exactly what the issue was for me.

**Comment by Mati36** [comment]
I solved this error by adding {} in this way 
return(
    <NavigationContainer>{ ChatStack/> }<NavigationContainer>
  );

**Comment by Mati36** [comment]
I solved this error by wrapping my component with {} like so
return(
    <NavigationContainer>{ <ChatStack/> }</NavigationContainer>
);

**Comment by Mati36** [comment]
I solved this error by wrapping my component with {} like so
return(
    <NavigationContainer>{ <Chat/> }</NavigationContainer>
);

**Comment by Mati36** [comment]
I solved this error by wrapping my component with {} like so

```
return(
    <NavigationContainer>{ <Chat/> }</NavigationContainer>
);
```

**Comment by Google-Repo** [comment]
> import { NavigationContainer } from '@react-navigation/native'; 
plz write  this "import {navigationContainer} from '@react-navigation/native;"

i think it may work

**Comment by sermetoztoprak** [comment]
> Bileşenimi şöyle {} ile sararak bu hatayı çözdüm
> 
> ```
> return(
>     <NavigationContainer>{ <Chat/> }</NavigationContainer>
> );
> ```

Yes it worked. thanks

**Comment by wenboBcoder** [comment]
https://reactnavigation.org/docs/tab-based-navigation

**Comment by kiyasov** [comment]
Deleting the node_modules folder and reinstalling the modules worked for me
