### ISSUE TITLE
navigationRef.current.push is not a function. (In 'navigationRef.current.push(name, params)', 'navigationRef.current.push' is undefined)

### ISSUE THREAD

**Issue by mohmdalfaha** [react-navigation/react-navigation-4#6648]
### Current Behavior
refering https://reactnavigation.org/docs/en/next/navigating-without-navigation-prop.html
Using the push() action with navigationRef is throwing undefined but if I use navigate() it works fine
```
import * as React from 'react';

export const navigationRef = React.createRef();

export function navigate(name, params) {
  navigationRef.current && navigationRef.current.navigate(name, params);
}

export function push(name, params) {
  navigationRef.current && navigationRef.current.push(name, params);
}
```
### Expected Behavior

I want to use push() to move to the other screen inside a context provider

### How to reproduce
inside app.js
```
=======
import {navigationRef} from './src/Navigations/navigationRef';
import { NavigationNativeContainer } from '@react-navigation/native';

export default function App(props) {
======
return (
      <NavigationNativeContainer ref={navigationRef}>
        <AuthProivder>
              <AppNavigator  />
        </AuthProivder>
      </NavigationNativeContainer>

  )
```

inside the navigationRef file

```
import * as React from 'react';

export const navigationRef = React.createRef();

export function navigate(name, params) {
  navigationRef.current && navigationRef.current.navigate(name, params);
}

export function push(name, params) {
  navigationRef.current && navigationRef.current.push(name, params);
}
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-navigation-stack | 2.0.0-alpha.6
| react-native     | 35.0.0
| expo             | 35.0.0
| node             | v12.12.0
| npm or yarn      | yarn

**Comment by MuhammadTayyabDev** [comment]
please try to console navigationRef and then navigationRef.current ...

you will find a reference chain a navigationRef.current._navigation.navigate(name);

**Comment by alimertcakar** [comment]
I've got 
```
{
    "current": null
}

```
on navigationRef. What could be the issue?
