### ISSUE TITLE
Screen does not appear but is still mount (combination NativeStackNavigator and TabNavigator)

### ISSUE THREAD

**Issue by AlexandreMaistret** [react-navigation/react-navigation-4#6656]
### Current Behavior

I am running a nested NativeStackNavigator inside a BottomTabNavigator. When I go on the 2nd screen of the nested NativeStackNavigator, and then go back to the Tab navigator, switch to another tab, then go back to the initial tab and try to go again to the 2nd screen of the nested NativeStackNavigator, the 2nd screen does not appear on the device.

Here is a diagram for better understanding :

TabNavigator: 
- tab A
- tab B
- tab C
- tab D
- tab E (the nested StackNavigator)

E Nested NativeStack:
- screen 1
- screen 2

The TabNavigator starts on tab C.
I do `tab C `=> `tab E (screen 1)` => `screen 2` it works fine
Then I do `screen 2` => `screen 1 (tab E)` =>`tab D` => `screen 1 (tab E)` => `screen 2`, and the last `screen 2` never appears, but the `componentDidMount` in `screen 2` is called, and when I press the backButton on the android device, `componentWillUnmount` of `screen 2` is called.

### Expected Behavior

I am expecting to be able to go on 2nd screen of the nested NativeStackNavigator at any time.

### How to reproduce

    const MainStack = createNativeStackNavigator();
    const MainTab = createBottomTabNavigator();
    const TabEStack = createNativeStackNavigator();

    function MainTabScreens() {
      return (
        <MainTab.Navigator
          initialRouteName='ScreenC'
          screenOptions={{
            headerShown: false,
            gestureEnabled: false,
          }}
          tabBar={(props) => {
           return (
             <NavigateBar
               navigation={props.navigation}
             />
           );
          }}
        >
          <MainTab.Screen
            name="ScreenA"
            component={ScreenA}
          />
          <MainTab.Screen
            name="ScreenB"
            component={ScreenB}
          />
          <MainTab.Screen
            name="ScreenC"
            component={ScreenC}
          />
          <MainTab.Screen
            name="ScreenD"
            component={ScreenD}
          />
          <MainTab.Screen
            name="TabEScreens"
            component={TabEScreens}
          />
        </MainTab.Navigator>
      );
    }

    function TabEScreens() {
      return (
        <TabEStack.Navigator
          initialRouteName='Screen1'
          screenOptions={{
            headerShown: false,
            gestureEnabled: false,
          }}
        >
          <TabEStack.Screen
            name="Screen1"
            component={Screen1}
          />
          <TabEStack.Screen
            name="Screen2"
            component={Screen2}
            options={{ tabBarVisible: false }}
          />
        </TabEStackNavigator>
      );
    }

    function App() {
      return (
        <MainStack.Navigator
           initialRouteName='SplashScreen'
           screenOptions={{
            headerShown: false,
            gestureEnabled: false,
           }}
         >
           <MainStack.Screen
             name="SplashScreen"
             component={SplashScreen}
           />
           <MainStack.Screen
             name="MainTabScreens"
             component={MainTabScreens}
           />
        </MainStack.Navigator>
      )
    }

Here is a gif of the problem:

The steps in the gif:
- the gif starts on the tab E (screen 1)
- I press on the gearing top right, and I have screen 2,
- I press back in screen 2 and I go back on tab E (screen 1).
- I press on the TabBar to go on tab D
- I press on the TabBar to go back on tab E
- Then I try to go on screen 2 by pressing the gear again and it does not work

As you can see, something is still hapening, the StatusBar color changes, because on screen 2 I change the color of the status bar in `componentDidMount` in screen 2. So screen 2 is rendered somehow, but not shown on the screen.

![bug_navigation (1)](https://user-images.githubusercontent.com/14938428/71563695-302cf300-2a94-11ea-87f5-37ec359b4509.gif)

Moreover, to hide the TabBar in `screen 2`, I tried to put the Screen 2 in the MainStack, as it is recommanded in the docs ([link](https://reactnavigation.org/docs/en/next/screen-options-resolution.html#setting-parent-screen-options-based-on-child-navigators-state)) so like this : 

    const MainStack = createNativeStackNavigator();
    const MainTab = createBottomTabNavigator();

    function MainTabScreens() {
      return (
        <MainTab.Navigator
          initialRouteName='ScreenC'
          screenOptions={{
            headerShown: false,
            gestureEnabled: false,
          }}
          tabBar={(props) => {
           return (
             <NavigateBar
               navigation={props.navigation}
             />
           );
          }}
        >
          <MainTab.Screen
            name="ScreenA"
            component={ScreenA}
          />
          <MainTab.Screen
            name="ScreenB"
            component={ScreenB}
          />
          <MainTab.Screen
            name="ScreenC"
            component={ScreenC}
          />
          <MainTab.Screen
            name="ScreenD"
            component={ScreenD}
          />
          <MainTab.Screen
            name="ScreenE"
            component={ScreenE}
          />
        </MainTab.Navigator>
      );
    }

    function App() {
      return (
        <MainStack.Navigator
           initialRouteName='SplashScreen'
           screenOptions={{
            headerShown: false,
            gestureEnabled: false,
           }}
         >
           <MainStack.Screen
             name="SplashScreen"
             component={SplashScreen}
           />
           <MainStack.Screen
             name="MainTabScreens"
             component={MainTabScreens}
           />
          <MainStack.Screen
             name="Screen2"
             component={Screen2}
           />
        </MainStack.Navigator>
      )
    }

And with this configuration, it is the opposite, the TabNavigator does not show the correct screen, but the screen in somehow again focused since the StatusBar change (I use useFocusEffect to execute the function when the screen is focused)

![bug_navigation2](https://user-images.githubusercontent.com/14938428/71563804-f6f58280-2a95-11ea-860a-b86c30e6bffa.gif)

I tried to create an expo app with the same problem but I didn't manage to show a TabNavigator on expo, I have a white screen even with the example code of the docs. However with a StackNavigator no problem. I don't know why it is not working.

I didn't tried with an Iphone since I focus only on Android. I tried with an emulator and a real device, and I have exactly the same problem on both.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  5.0.0-alpha.21
| react-native     |  0.60.5
| node             |  10.16.3
| react-native-screens  |  2.0.0-alpha.22

**Comment by mezhik91** [comment]
I have the same issue with next versions:

"@react-navigation/native": "^5.1.5",
"@react-navigation/stack": "^5.2.10",
"react-native-screens": "2.4.0",

Hover downgrade of react-native-screens to 2.1 fix the issue
