### ISSUE TITLE
createDrawerNavigator error core.createNavigator factory is not a function

### ISSUE THREAD

**Issue by jeypc** [react-navigation/react-navigation-4#6659]
Hi, I got this error when trying to implement createDrawerNavigator on IOS simulator

### Current Behavior

This is my code:

SignInNav.js
```javascript
import { createDrawerNavigator } from '@react-navigation/drawer';
import { NavigationNativeContainer } from '@react-navigation/native';
import Beranda from './Beranda'

const Drawer = createDrawerNavigator();
const SignInNav = () => {
  return (
    <NavigationNativeContainer>
      <Drawer.Navigator initialRouteName="Beranda">
        <Drawer.Screen name="Beranda" component={Beranda} />
      </Drawer.Navigator>
    </NavigationNativeContainer>
  )
}

export default SignInNav
```

App.js
```javascript
import React, { Component } from 'react';
import SignOutNav from './src/navigation/SignoutNav';
import SignInNav from './src/navigation/SignInNav'
import { connect } from 'react-redux';

class App extends Component {
  render() {
    const { auth } = this.props
    return auth.isLoggedIn ? (
      <SignInNav />
    ) : (
        <SignOutNav />
      )
  }
}

const mapStateToProps = (state) => {
  return {
    auth: state.auth
  }
}

export default connect(mapStateToProps)(App);

```

This is what I get

![](https://i.ibb.co/fHfRN5M/Simulator-Screen-Shot-i-Phone-11-2019-12-24-at-21-37-45.png)

### Your Environment

"@react-navigation/drawer": "^5.0.0-alpha.23",
"@react-navigation/native": "^5.0.0-alpha.21",
"@react-navigation/stack": "^5.0.0-alpha.46",
"react": "16.9.0",
"react-native": "0.61.5"

System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 124.32 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.2 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.1
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by amranwebdeveloper** [comment]
Face same the same error. Got it resolved. Try with this:

npm install @react-navigation/native

or

yarn add @react-navigation/native@next

or

yarn add @react-navigation/native

Doc: https://reactnavigation.org/docs/getting-started/

**Comment by adrianmcg85** [comment]
I’m getting ‘failed to compile’
Support for the experimental syntax ‘jsx’ isn’t currently enabled.
