### ISSUE TITLE
Changing background on tab navigator doesn't change safe area inset background

### ISSUE THREAD

**Issue by klase** [react-navigation/react-navigation-4#6663]
---

### Current Behavior

Adding a tab navigator on a phone with a bottom inset (ie Iphone 11 Pro) and changing the backgroundColor prop on tabStyle results in a grey bar below the tabs.

![Screenshot 2019-12-18 at 11 02 44](https://user-images.githubusercontent.com/1711650/71081581-69f22580-2187-11ea-83fa-bee85e8f496d.png)

### Expected Behavior

Changing background color should also change the inset background.

### How to reproduce
```
<Tab.Navigator
  tabBarOptions={{
            tabStyle: {
              backgroundColor: "blue"
            }
          }}
        >
 <Tab.Screen name="Feed" component={Feed} />
 <Tab.Screen name="Article" component={Article} />
</Tab.Navigator>
```

### Your Environment

@react-navigation/bottom-tabs 5.0.0-alpha.22
@react-navigation/core ^5.0.0-alpha.25

**Comment by kierangillen** [comment]
@klase Could you please add a solution if this was solved, thanks.

**Comment by klase** [comment]
@kierangillen the solution was to add the backgroundColor prop on the style key on tabBarOptions as well

```
<Tab.Navigator
  tabBarOptions={{
            tabStyle: {
              backgroundColor: "blue"
            },
            style: {
              backgroundColor: "blue"
            }
          }}
        >
 <Tab.Screen name="Feed" component={Feed} />
 <Tab.Screen name="Article" component={Article} />
</Tab.Navigator>
```

**Comment by The0racle** [comment]
How can one achieve this on v6?
