### ISSUE TITLE
Issue with TypeScript Class component | ReactNavigation 5 | ReactNative

### ISSUE THREAD

**Issue by ImAbhishekTomar** [react-navigation/react-navigation-4#6664]
i am having belorw issue with React Navigation 5 , anyone please help.

Thanks in advance

**Issue**
![4862F9EB-6F0D-4B15-8B27-BFB9423BAF3D](https://user-images.githubusercontent.com/6933841/71034418-5f6a6880-2154-11ea-80e0-c3ccf2ddb5da.jpeg)

**Error Message**
(property) Screen: <RouteName extends string>(\_: RouteConfig<Record<string, object | undefined>, RouteName, StackNavigationOptions>) => null

Component used for specifying route configuration.

Type '{ name: "ScreenSignUp"; component: typeof SignupContainer; }' is not assignable to type '(IntrinsicAttributes & { name: "ScreenSignUp"; options?: StackNavigationOptions | ((props: { route: RouteProp<Record<string, object | undefined>, "ScreenSignUp">; navigation: any; }) => StackNavigationOptions) | undefined; initialParams?: object | undefined; } & { ...; }) | (IntrinsicAttributes & ... 1 more ... & { ...'.Type '{ name: "ScreenSignUp"; component: typeof SignupContainer; }' is not assignable to type '{ component: ComponentType<{ route: RouteProp<Record<string, object | undefined>, "ScreenSignUp">; navigation: any; }>; }'.Types of property 'component' are incompatible.Type 'typeof SignupContainer' is not assignable to type 'ComponentType<{ route: RouteProp<Record<string, object | undefined>, "ScreenSignUp">; navigation: any; }>'.Type 'typeof SignupContainer' is not assignable to type 'ComponentClass<{ route: RouteProp<Record<string, object | undefined>, "ScreenSignUp">; navigation: any; }, any>'.Types of parameters 'props' and 'props' are incompatible.Type '{ route: RouteProp<Record<string, object | undefined>, "ScreenSignUp">; navigation: any; }' has no properties in common with type 'Readonly<Readonly<StackNavigationOptions>>'.ts(2322)

**Comment by tamangsuresh** [comment]
I use generic according to doc. But it's still showing red line.
<img width="592" alt="Screen Shot 2020-06-04 at 3 30 49 PM" src="https://user-images.githubusercontent.com/21368268/83741797-617ba180-a678-11ea-90ed-2a14139ed905.png">

**Comment by Pragati20** [comment]
@tamangsuresh I am also facing the same issue even after type declaration.If you have got any solution then please share.
