### ISSUE TITLE
navigation.navigate does not reset route params

### ISSUE THREAD

**Issue by kbrandwijk** [react-navigation/react-navigation-4#6674]
---

### Current Behavior

I have a screen that's part of a bottomTabNavigator. I have two ways of navigating to this screen:

- Tapping somewhere on one of the screens calls `navigation.navigate('MyScreen', { myParam: 'value' })`
- Tapping on the button in the bottom tabbar

Now as soon as I've navigated to the screen once _with_ a route parameter, I have no way of resetting this param. The next time I use the tabbar button, the screen will still have that value in `route.params.myParam`. Even using `unmountInactiveScreens` to completely get rid of the screen doesn't clear the route param.

To isolate the issue from the tabbar, I also added a direct call to `navigation.navigate('MyScreen')`, and noticed the route param also not reset.

### Expected Behavior

Subsequently navigating to a screen without specifying any route params should clear the previous ones.

### How to reproduce

https://snack.expo.io/@agartha/route-params

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 5.0.0-alpha.24 (core), .16 (native), .37 (stack)
| react-native     | 0.61.5
| expo             | -
| node             | 11.12.0
| yarn      | 1.15.2

**Comment by dantasfiles** [comment]
> You can add a listener on `tabPress` where you can reset the param with `setParams` inside your screen.

There are two versions in the documentation

[Documentation version](https://reactnavigation.org/docs/en/bottom-tab-navigator.html#tabpress) with `useEffect` hook:
```javascript
React.useEffect(() => {
  const unsubscribe = navigation.addListener('tabPress', e => {
    // Prevent default behavior
    e.preventDefault();
    // Do something manually
    // ...
  });
  return unsubscribe;
}, [navigation]);
```

[Snack version](https://snack.expo.io/?platform=android&name=createBottomTabNavigator%20%C2%B7%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.1%2C%40react-navigation%2Fnative%405.0.4%2C%40react-navigation%2Fbottom-tabs%405.0.4%2C%40react-navigation%2Fdrawer%405.0.4%2C%40react-navigation%2Fmaterial-bottom-tabs%405.0.4%2C%40react-navigation%2Fmaterial-top-tabs%405.0.4%2C%40react-navigation%2Fnative-stack%405.0.4%2C%40react-navigation%2Fstack%405.0.4%2Creact-native-gesture-handler%401.5.2%2Creact-native-reanimated%401.4.0%2Creact-native-safe-area-context%400.6.0%2Creact-native-screens%402.0.0-alpha.12&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fbottom-tab-prevent-default.js):
```javascript
function HomeScreen({ navigation }) {
  navigation.addListener('tabPress', e => {
    // Prevent default behavior
    e.preventDefault();
    alert('Default behavior prevented');
    // Do something manually
    // ...
  });
  ...
```

Which is correct? Are there any downsides to using one or the other?

**Comment by mykhailo-riabokon** [comment]
Hi there!

I faced a similar issue and could achieve the expected results by deleting `param` from `params`.

Let's say I have an app with three tabs, the last third tab is a stack navigation where default route is set by param from navigation params.

```jsx
const Tabs = createBottomTabNavigator();

const RootLevelTabs = () => {
    // const navigator = useNavigation();  will not work to get navigator, as it's not inside Screen
    // const navigator = useContext(NavigationContext); the same as above

    return (
        <NavigationContainer>
            <Tabs.Navigator>
                <Tabs.Screen
                    name="Screen1"
                    component={Screen1}
                />
                <Tabs.Screen
                    name="Screen2"
                    component={Screen2}
                />
                <Tabs.Screen
                    name="Screen3"
                    component={ScreenYouNeedNavPropOnlyOnce}
                    options={{ unmountOnBlur: true }}
                    listeners={{
                        tabPress: (event) => {
                            event.preventDefault(); // works as expected, default redirect will not happen

                            // Ideally create an action and dispatch with params you do not need anymore, like
                            const action = TabActions.jumpTo('Screen3', { paramYouNeed: null });
                            
                            navigator.dispatch(action);

                            // but as it's impossible to get navigator in here, it will not work :pepe_sad
                            // check ScreenYouNeedNavPropOnlyOnce
                        }
                    }}
                />
            </Tabs.Navigator>
        </NavigationContainer>
    )
};
```
First try was to re-write `tabPress`, so I would reset param I do not need once redirect happens by pressing on a tab, but it does not work as `navigator` can not be defined on that that level.

```jsx
const ScreenYouNeedNavPropOnlyOnce = (props) => {
    const [defaultScreen, setDefaultScreen] = useState('First')
    const { navigation } = props;
    const { params } = props.route;

    if (params && 'paramYouNeed' in params) {
        // do some things here, like save it in state
        // and delete paramYouNeed from params, as it was used already

        // navigation.setParams({ paramYouNeed: null }) triggres re-render of this screen, 
        // navigation.navigate('Screen3', { paramYouNeed: undefined }) also re-renders 

        setDefaultScreen('Second')

        delete params.paramYouNeed;
        // it works, and next time user presses tab, params.paramYouNeed is not set
        // but it's very tricky, as it depends on mutability of params object
    }

    // Stack navigation in here
    // ...
};
```

As result `delete params.paramYouNeed;` did the trick, but it's more a hack than a solution.

**Comment by jtomaszewski** [comment]
It's a bit weird default behaviour. At least, could we have an option or something to customize this behaviour? Currently I have to do something like this in all parts of my code:

```
navigation.navigate(screen, {
  // Nullify all params so they aren't kept from the previous route
  // ( https://github.com/react-navigation/react-navigation/issues/6674 )
  paramA: undefined,
  paramB: undefined,
  paramC: undefined,
  ...params
});
```

Which isn't ideal because it forces me to have an additional helper that wraps the `navigation.navigate()` method, and requires me to memorize all the param keys I use in all my routes.

**Comment by jtomaszewski** [comment]
FYI I've done a utility function that changes the `navigate()` behaviour. At least we have a workaround for now. (I'd be happy to contribute with a PR to `react-navigation` though.)

```tsx
import {
  useNavigation as useReactNavigation,
  NavigationProp,
  ParamListBase
} from "@react-navigation/native";
import { useMemo } from "react";

/**
 * Changes the behaviour of `navigate()` so that it replaces the current route params,
 * instead of merging them.
 *
 * https://github.com/react-navigation/react-navigation/issues/6674#issuecomment-665006548
 */
export function useNavigation
  T extends NavigationProp<ParamListBase>
>(): T {
  const navigation = useReactNavigation<T>();

  return useMemo((): any => {
    function getEmptyParams(): object {
      const state = navigation.dangerouslyGetState();
      const keys: string[] = Array.prototype.concat(
        ...state.routes.map((route) =>
          Object.keys((route as any)?.params || {})
        )
      );
      return keys.reduce((acc, k) => ({ ...acc, [k]: undefined }), {});
    }

    const navigate: typeof navigation.navigate = (...args: any) => {
      if (typeof args[0] === "string") {
        return navigation.navigate(args[0], {
          ...getEmptyParams(),
          ...args[1]
        });
      }

      if (typeof args[0] === "object") {
        return navigation.navigate({
          ...args[0],
          params: {
            ...getEmptyParams(),
            ...args[0].params
          }
        });
      }

      return navigation.navigate(...args);
    };

    return {
      ...navigation,

      navigate
    };
  }, [navigation]);
}
```

**Comment by VictorioMolina** [comment]
Same behavior when doing .push() to the same route in which there are already set parameters without just passing them. It would be nice if this did not happen, I am forced to restart them whenever I want to navigate to a route with parameters.

**Comment by wangyi7099** [comment]
> This is expected behaviour. Params are always merged. If you want to reset a param, you can explicitly set it to `undefined`:
> 
> ```js
> navigation.navigate('MyScreen', { myParam: undefined })
> ```

I think we should not merge , and we should replace the params or at least allow user to control `merge` or `replace`...

**Comment by kbrandwijk** [comment]
It's been a good  year since I ran into the issue, and tried using the workarounds for explicitly passing in undefined, and I've come to the same conclusion: the default behavior, which cannot be controlled or configured, is undesirable in most cases where there's multiple flows to the same screen. In fact, I've never ran into a use case where the default behavior was desireable, on multiple large and complex apps. 

I wouldn't mind having an optional parameter to `navigate` to control parameter behavior with possible values 'clear', 'merge', and 'replace'. If there's enough support for it, I wouldn't even mind looking into how to implement that.

**Comment by mikehardy** [comment]
Just noting 26 thumbs up is the most reactions I've seen to a simple comment in a long time, even on react-native core issues. I would love to have a parameter that let me choose to 'replace' vs 'merge'. I'm busy writing a param un-definer script right now, with the use case that there is a general search box at top of my app that can hit a stack screen that is a tab on a tab navigator, but also there's another tab where an advanced search can be done - both lead to same results but each needs to clear params of the other :shrug:

**Comment by kbrandwijk** [comment]
@mikehardy I think it finally made its way in some form into react-navigation 6...

![image](https://user-images.githubusercontent.com/852069/125723438-9091329a-eeb3-4f29-bb04-0d53a7404dba.png)

It's not exactly the same, but at least passing an empty parameters object will replace the existing params, so it sounds like it fits your usecase.

**Comment by mikehardy** [comment]
Huh, I swear I tried that and undefined and it didn't work. I'm on current stable, I will double check everything thanks for the heads up

**Comment by kbrandwijk** [comment]
> Huh, I swear I tried that and undefined and it didn't work. I'm on current stable, I will double check everything thanks for the heads up

Current stable is 5.x, this is new in 6 (so @next)

**Comment by realtux** [comment]
even react navigation 6 still seems to merge. i feel extraordinarily dirty having to solve it this way, but, here is what i did:

```js
class TopLevelNav {

    default_params = {}

    do_navigate(navigator, screen, params = {}) {
        for (const param in params) {
            this.default_params[param] = undefined;
        }

        navigator.navigate('Stack', {
            screen,
            params: {
                ...this.default_params,
                ...params,
            },
        });
    }

}
```

**Comment by liquidvisual** [comment]
Spent a few hours before I realised route params merge. Why would anyone ever want that merged? Who designed this?!

**Comment by mikehardy** [comment]
@liquidvisual don't be rude. A hot-take in a repo from someone who has never contributed to the repo they freely use seems a bit out of bounds.

**Comment by realtux** [comment]
this is the nature of open source, it's not the end of the world, just make a workaround like i did.

**Comment by liquidvisual** [comment]
@mikehardy you're right, I apologise. Long day got the better of me.

**Comment by fukemy** [comment]
still problem to me. for example.
1. I pass message params to forwardscreen from chatscreen
2. In forwardscreen, i modified some data
3. Back to chatscreen
4. Navigate to forwardscreen again, this data does not renew even im using spread operator to pass new params

**Comment by meenabassem** [comment]
@mykhailo-riabokon I think now at least you can use the navigation 


[listeners prop on Screen​](https://reactnavigation.org/docs/navigation-events/#listeners-prop-on-screen)

```jsx
<Tab.Screen
  name="Chat"
  component={Chat}
  listeners={({ navigation, route }) => ({
    tabPress: (e) => {
      // Prevent default action
      e.preventDefault();

      // Do something with the `navigation` object
      navigation.navigate('AnotherPlace');

      // or, just delete the prop from the route instead of the above lines
      delete route.params?.param_to_delete
    },
  })}
/>
```

**Comment by filiptdz** [comment]
The new approach is perfect, but it's only seems to be documented in the upgrading docs. In all the other references to `navigation.navigate` on the docs, I could only find the usage as `navigate(name)`, and no suggestions that you could instead pass an object like `navigate({ name, merge: true })`. The typescript typings and jsdoc annotations also lead to a similar conclusion

**Comment by wangyi7099** [comment]
已收到

**Comment by fukemy** [comment]
I have solution, just use useEffect with <b>routes</b> is dependency, when route changed and replace current screen with new route params

**Comment by kevinchristianto** [comment]
> I have solution, just use useEffect with routes is dependency, when route changed and replace current screen with new route params

ah it helps, thanks!

**Comment by Y3KC3** [comment]
this worked for me

```
<Drawer.Screen
          name={.....}
          component={....}
          options={{ .... }}
          listeners={({ navigation }) => ({ blur: () => navigation.setParams({ name: null, ref: null }) })} // Add this
 />
```

**Comment by jackylu0124** [comment]
Hi @kbrandwijk @satya164, is there any plan to continue supporting the `merge` option in `navigate()` in React Navigation 7.x? I checked the React Navigation 7.x documentation, but could not find the `merge` option in `navigate()` examples likes the ones in React Navigation 6.x documentation. Thanks in advance!
