### ISSUE TITLE
Stale state data calling a function from a header button with useEffect

### ISSUE THREAD

**Issue by kbrandwijk** [react-navigation/react-navigation-4#6675]
### Current Behavior

1. In my function component, I use `navigation.setOptions` to set headerRight to a `TouchableOpacity` using `useEffect`. The `onPress` points to a local function in my component.
2. I use the `useState` hook to keep track of some state information, that changes due to things happening on the screen (not too relevant how, it's just normal `useState` usage)
3. Whenever I press the button in the header, the function that is called accesses this state variable, and that variable does not return the most recent value, in other words, it has the value it had when `navigation.setOptions` was called.
4. I confirmed this by adding my state variable to the `useEffect` variables array, effectively re-calling `setOptions` every time it changes. Now, when the function is called, the state variable does have the latest value.

If I use `useFocusEffect` instead of `useEffect`, it works fine: I'm unsure why `useEffect` doesn't work, my reasoning was: I don't need `useFocusEffect`, because I don't have to set these navigationOptions every single time the screen focuses, just once, when it's created.

I'm not 100% comfortable and intimate yet with that whole new hooks lifecycle stuff, but hopefully this makes sense to someone. 

### Expected Behavior

I would expect the function called by the header button to have access to the _current_ context, instead of what seems like a 'snapshot' of when it was set.

### How to reproduce

https://snack.expo.io/@agartha/trusting-chocolates-2 with `useEffect` (does not work)
https://snack.expo.io/@agartha/trusting-chocolates with `useFocusEffect` (works)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 5.0.0-alpha.24 (core), .16 (native), .37 (stack)
| react-native     | 0.61.5
| expo             | -
| node             | 11.12.0
| yarn      | 1.15.2

**Comment by macfanatic** [comment]
I agree this is very confusing and I'm in the same situation:

- a date component sets state
- `useEffect` when function component mounted to set my `headerRight` button
- `onPress` is a local function, referencing the state variable

When pressing, the state variable is stale.  I expected passing the function reference to work, as it would in any other situation.  I can only assume my button and the local function are being cached?

**Comment by mir1198yusuf** [comment]
Even I am facing a similar situation.
One workaround for me was to set headerRight everytime state variables changes by tracking it in React.useEffect for that state dependency.

**Comment by fdegrave** [comment]
Yeah, same here. In fact the reason they closed this issue is even in contradiction with [the doc](https://reactnavigation.org/docs/header-buttons/). I too had to change my `useLayoutEffect into a `useEffect` with dependencies.

**Comment by ragasjohn** [comment]
> Even I am facing a similar situation. One workaround for me was to set headerRight everytime state variables changes by tracking it in React.useEffect for that state dependency.

Hello there, 
I am on the same situation here. Can you share an example please?

**Comment by widescape** [comment]
> I am on the same situation here. Can you share an example please?

```es6
  const [count, setCount] = useState(0)

  useLayoutEffect(() => {
    navigation.setOptions({
      headerTitle: `Count is ${count}`,
      headerRight: () => <Button title="Increase" onPress={() => setCount(count + 1)} />,
    })
  }, [navigation, count]) // ← This `count` here ensures that the header state is updated
```

**Comment by ragasjohn** [comment]
> > I am on the same situation here. Can you share an example please? — @ragasjohn
> 
> ```js
>   const [count, setCount] = useState(0)
> 
>   useLayoutEffect(() => {
>     navigation.setOptions({
>       headerTitle: `Count is ${count}`,
>       headerRight: () => <Button title="Increase" onPress={() => setCount(count + 1)} />,
>     })
>   }, [navigation, count]) // ← This `count` here ensures that the header state is updated
> ```

Thanks this did the trick

Sorry for talking on a closed issue. Will not happen again!

**Comment by darren4flow** [comment]
An alternate solution is to set headerShown to false in the screen options and add a custom header to the top of your component. This was the best solution for me because I wanted to add a Save button to my header on the right. if I set the headerRight in navigation.SetOptions() in a useEffect then I would have had a lot of side effects because I would need a large dependency array to ensure my handleSave didn't have stale state values.
