### ISSUE TITLE
How to lock Drawer to a single screen when Drawer is the parent navigator?

### ISSUE THREAD

**Issue by nextriot** [react-navigation/react-navigation-4#6680]
### Current Behavior

I currently wrap a `MaterialBottomTabNavigator` within a `DrawerNavigator`'s `DrawerScreen` - I do this so that the Drawer will present itself on top of the Tab Bar. I want the ability to use gestures to show and hide the drawer, but only from within **one of the screens within the tab bar**.

The issue is that if I enable gestures on the `DrawScreen` the gesture is available anywhere in the tab navigator. I've attempted the following:

- listen for `tabPress` events using `useEffect` or `useFocusEffect` to enable / disable gestures on focus / blur, but I assume due to the nature of screens within `MaterialBottomTabNavigator` being mounted and never unmounted, the effect never fires twice.

- I've attempted to add `unmountInactiveScreens` on the `DrawerNavigator` but this also has no effect because the `MaterialBottomTabNavigator` is the component within the `DrawerScreen` and never becomes inactive.

- I've attempted to move it up a level by creating a custom drawer component and listening to changes on it, but it doesn't seem to expose the necessary route information, nor does setting the `gesture` option on it seem to have any effect.

- Lastly, I've also tried to use `dangerouslyGetParent` within the screens to lock the drawer, but again, with the screens never being unmounted, this is a noop.

- Include a screenshot if it makes sense.

### Expected Behavior

I expect the ability to lock a drawers visibility to a certain screen within its stack, and / or present a child drawer navigator over the top of all UI.  

### How to reproduce

Here's the full navigator source code for completeness:

```
import React, { useContext } from 'react'
import { createMaterialBottomTabNavigator } from '@react-navigation/material-bottom-tabs'
import { createStackNavigator } from '@react-navigation/stack'
import { createDrawerNavigator } from '@react-navigation/drawer'

import { ThemeContext } from 'styled-components'

import { ThemeProps } from 'theme/types'
import { NavOptions } from 'utils'

import Dashboard from 'screens/Agent/Dashboard'
import Settings from 'screens/Agent/Settings'
import Trips from 'screens/Agent/Trips'

import ConversationsDrawer from './ConversationsDrawer'

const Tab = createMaterialBottomTabNavigator()
const Stack = createStackNavigator()
const Drawer = createDrawerNavigator()

const AgentTabs = () => {
  const theme: ThemeProps = useContext(ThemeContext)
  return (
    <Tab.Navigator
      shifting
      labeled={false}
      activeColor={theme.accent.icon.on}
      inactiveColor={theme.accent.icon.off}
      initialRouteName="AgentTrips"
      barStyle={NavOptions.RemoveTabSeparatorStyle(theme)}>
      <Tab.Screen
        name="AgentDashboard"
        component={Dashboard}
        options={NavOptions.BottomTabScreen({ icon: 'dashboard' })}
      />
      <Tab.Screen name="AgentTrips" component={Trips} options={NavOptions.BottomTabScreen({ icon: 'trips' })} />
      <Tab.Screen name="AgentMore" component={Settings} options={NavOptions.BottomTabScreen({ icon: 'more' })} />
    </Tab.Navigator>
  )
}

const AgentDrawer = () => {
  return (
    <Drawer.Navigator
      drawerPosition="left"
      drawerType="front"
      drawerContent={props => <ConversationsDrawer {...props} />}>
      <Drawer.Screen
        name="AgentApp"
        component={AgentTabs}
        options={{
          gestureEnabled: true,
        }}
      />
    </Drawer.Navigator>
  )
}

const AgentStack = () => {
  return (
    <Stack.Navigator headerMode="none" mode="modal">
      <Stack.Screen name="AgentApp" component={AgentDrawer}></Stack.Screen>
      <Stack.Screen name="AgentSearch" component={AgentTabs}></Stack.Screen>
    </Stack.Navigator>
  )
}

export default AgentStack
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 5.0.0-alpha.24
| react-native     | 0.59
| expo             | 35.0.0
| node             | 10.16.0
| yarn      | 1.10.1

**Comment by AmirHMousavi** [comment]
@satya164 Does this approach sounds logical to you? Why version 5 does not have `drawerLockMode `

**Comment by rajeevsharmacoder** [comment]
> ```js
> // In your navigator
> <Drawer.Navigator screenOptions={{ gestureEnabled: false }}>
> 
> // ...
> 
> // In your screen where you want it to be enabled
> useFocusEffect(
>   React.useCallback(() => {
>     const parent = navigation.dangerouslyGetParent();
> 
>     parent.setOptions({ gestureEnabled: true });
> 
>     return () => parent.setOptions({ gestureEnabled: false });
>   }, [navigation])
> );
> ```

Thank you, this worked for me.

**Comment by molimat** [comment]
If you have a deep nested stack navigator, maybe you have to do something like this:

 ```
HomeTab: {
      screen: HomeTab,
      navigationOptions: ({ navigation }) => {
        return {
          drawerLockMode:
            navigation.getChildNavigation('Home').state.index === 0
              ? 'unlocked'
              : 'locked-closed',
        };
      },
      path: '',
    },
```

So you can access the state.index of your grandChildren :)

**Comment by imomer** [comment]
> ```js
> // In your navigator
> <Drawer.Navigator screenOptions={{ gestureEnabled: false }}>
> 
> // ...
> 
> // In your screen where you want it to be enabled
> useFocusEffect(
>   React.useCallback(() => {
>     const parent = navigation.dangerouslyGetParent();
> 
>     parent.setOptions({ gestureEnabled: true });
> 
>     return () => parent.setOptions({ gestureEnabled: false });
>   }, [navigation])
> );
> ```

For me the `gestureEnabled: false` was not working... so I came up with the following solution... 

`useFocusEffect(
    useCallback(() => {
      const parent = navigation.getParent();
      parent.setOptions({swipeEdgeWidth: 0});
      return () => parent.setOptions({swipeEdgeWidth: 50});
    }, [navigation]),
  );`
