### ISSUE TITLE
[Question] createNativeStackNavigator doesn't work like a SwitchNavigator

### ISSUE THREAD

**Issue by hyochan** [react-navigation/react-navigation-4#6683]
### Current Behavior

- What code are you running and what is happening?
   ```
    <NavigationNativeContainer>
      <Stack.Navigator>
        <Stack.Screen name="Screen1" component={Screen1} />
        <Stack.Screen name="Screen2" component={Screen2} />
        <Stack.Screen name="Screen3" component={Screen3} />
        <Stack.Screen name="Screen4" component={Screen4} />
      </Stack.Navigator>
    </NavigationNativeContainer>
   ```
- Include a screenshot if it makes sense.

### Expected Behavior

- What do you expect should be happening?
   `createNativeStackNavigator` to work like a `SwitchNavigator`. It works like a `StackNavigator`.
- Include a screenshot if it makes sense.
   ![jIt8o2pWCv](https://user-images.githubusercontent.com/27461460/69479963-b4ada580-0e46-11ea-91dd-b651aad1d6e0.gif)

### How to reproduce
- Navigate from `Screen1` to `Screen2`. Also tried `push`.

### Your Environment
```
    "@react-navigation/core": "^5.0.0-alpha.24",
    "@react-navigation/native": "^5.0.0-alpha.14",
    "@react-navigation/native-stack": "^5.0.0-alpha.14",
    "@react-navigation/stack": "^5.0.0-alpha.20",
```
| software         | version
| ---------------- | -------
| react-navigation | 5.0.0-alpha
| react-native     | 0.61.4
| expo             | nope
| node             | 12.10.0
| npm or yarn      | 1.17.3

**Comment by Evanion** [comment]
@satya164 That link is no longer available, I have been unable to find any documentation relating to switch navigators in 5.x

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/upgrading-from-4.x.html#switch-navigator
