### ISSUE TITLE
Transition of NativeStack from big title to small title.

### ISSUE THREAD

**Issue by benevbright** [react-navigation/react-navigation-4#6687]
*Sorry for ignoring the template.

Hi, I'm trying to have a transition in NativeStack on iOS with `largeTitle` between large title and a small title. The transition by scrolling.
What's the plan? Is it implemented already and I just didn't find how to use it? Or is it in the roadmap of v5?

Should I ask about this at https://github.com/react-navigation/rfcs?

I like to contribute to this if possible.

Thanks.

**Comment by marcosrdz** [comment]
any updates on this?
