### ISSUE TITLE
Problem with `material-top-tabs` after device orientation change

### ISSUE THREAD

**Issue by KacperKozak** [react-navigation/react-navigation-4#6688]
### Current Behavior

- Tab screen and underline are placed incorrectly after device orientation change.
- Video with this problem: https://drive.google.com/file/d/1gx_iBcGVG65JgMxdfAWcTVeyK-D0AONm/view?usp=sharing

![image](https://user-images.githubusercontent.com/582227/68766897-07ee4f80-0620-11ea-8a3b-67663495cb4a.png)

### Expected Behavior

- Tabs should re-render after orientation change.

### How to Reproduce

1. Run very basic tab navigator eg:

```js
import React from 'react'
import { Text, View } from 'react-native'
import { createMaterialTopTabNavigator } from '@react-navigation/material-top-tabs'
import { NavigationNativeContainer } from '@react-navigation/native'

const Tab = createMaterialTopTabNavigator()

export const App = () => (
    <NavigationNativeContainer>
        <Tab.Navigator>
            <Tab.Screen name="Aaaaa" component={Screen} />
            <Tab.Screen name="Bbbbb" component={Screen} />
            <Tab.Screen name="Ccccc" component={Screen} />
        </Tab.Navigator>
    </NavigationNativeContainer>
)

const Screen = () => (
    <View style={{ borderColor: 'gray', borderWidth: 10, flex: 1 }}>
        <Text>Screen</Text>
    </View>
)

AppRegistry.registerComponent('App', () => App)
```

2. Change to the second tab
3. Rotate device
4. Re-try because sometimes the first attempt will work correctly

### Your Environment

* **Devices:** iOS and Android.
* **Versions:**
  ```
   "react": "16.9.0",
   "react-native": "0.61.2",
   "@react-navigation/core": "^5.0.0-alpha.22",
   "@react-navigation/material-top-tabs": "^5.0.0-alpha.17",
  ```

**Comment by damsonFilipson** [comment]
Problem still exists, at least on android
