### ISSUE TITLE
Missing TypeScript types for DrawerItemList

### ISSUE THREAD

**Issue by ManAnRuck** [react-navigation/react-navigation-4#6698]
## Current Behavior
Missing TypeScript exports for DrawerItemList to customise it with TypeScript

### Expected Behavior
make props export/importable
https://github.com/react-navigation/navigation-ex/blob/9d9fe31f0221242763fe22dafd7bc2cf014c592e/packages/drawer/src/views/DrawerItemList.tsx#L14-L18

software | version
-- | --
@react-navigation/core | 5.0.0-alpha.17
@react-navigation/drawer | 5.0.0-alpha.16
react-native | 0.61.2
expo | n/a
node | v12.9.1
npm or yarn | 6.10.2

**Comment by ucheNkadiCode** [comment]
The previous comment did not work for me. 

I solved this in typescript with 

export const CustomDrawer: React.FC<CustomDrawerProps> = ({ ...props }) => {
  const nav = useNavigation();
  return (
    <SafeAreaView style={{ flex: 1 }}>
      <DrawerContentScrollView {...props}>
        <DrawerItemList
          state={nav.getParent()}
          navigation={nav.getParent()}
          descriptors={nav.getParent()}
          {...props}
        />
      </DrawerContentScrollView>
    </SafeAreaView>
  );
};
