### ISSUE TITLE
resetOnBlur isn't implemented in bottomTabNavigator

### ISSUE THREAD

**Issue by mvrdrew** [react-navigation/react-navigation-4#6699]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report.

---

### Current Behavior

- What code are you running and what is happening?

When I try to use the resetOnBlur prop on the bottomTabNavigator, nothing happens (and TypeScript tells me the prop doesn't exist).

<img width="754" alt="Screenshot 2019-10-26 at 11 57 44" src="https://user-images.githubusercontent.com/54799983/67618473-07645500-f7e8-11e9-958c-c3009fce4679.png">

### Expected Behavior

- What do you expect should be happening?

resetOnBlur prop should exist and should be resetting the tab stack when pressed.

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

Create a bottomTabNavigator and add a stack as one of its screen. Add the resetOnBlur prop to the navigator.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 5.0.0-alpha.17
| react-navigation/bottom-tabs | 5.0.0-alpha.14
| react-native     | 0.61.2
| expo             | n/a
| node             | v12.9.1
| npm or yarn      | 6.10.2

--------

I've gone through the code and I can clearly see this prop hasn't been implemented yet, but I thought I'd raise this issue as it is included in the documentation.

**Comment by Tobbelobben** [comment]
@satya164 I am trying to do the same thing, but currently having the error that typescript cant find 'route'. Can I see the entire code to make this work?

I am currently trying to reset a stack navigator inside a tab navigator when I switch tabs.

**Comment by nathanbedford** [comment]
If you'd like to avoid the unmount penalty (takes a few extra milliseconds for me) you can subscribe to the 'blur' event and pop the nav stack to the top:

```
<BottomTab.Screen
  name={Screens.Home}
  component={HomeNavigator}
  options={{
    tabBarIcon: ({ color }) => <TabBarIcon name="ios-home" color={color} />,
  }}
  listeners={({ navigation, route }) => ({
    blur: () => {
      if (route.state && route.state.index > 0) {
        navigation.dispatch(StackActions.popToTop());
      }
    },
  })}
/>
```

This is the closest solution I've found to v3's `resetOnBlur`. Hope it helps!
