### ISSUE TITLE
[Android] Tab bar renders above keyboard

### ISSUE THREAD

**Issue by nhuesmann** [react-navigation/react-navigation-4#6700]
### Current Behavior

On Android, when the keyboard is shown, the bottom tab bar rises above the keyboard.

![gif](https://media.giphy.com/media/TfX4DjPNVXqQXWwRBw/giphy.gif)

### Expected Behavior

- The bottom tab bar should not move or animate
- I am currently using React Navigation 3 and this is not an issue
- I have also added the option `keyboardHidesTabBar: true` in the bottom tab bar navigator configuration, however that yields a janky animation.

### How to reproduce

Snack link: https://snack.expo.io/@nhuesmann/joyous-milkshake

### Your Environment

From `package.json`
```
"@react-native-community/masked-view": "^0.1.1",
"@react-navigation/bottom-tabs": "^5.0.0-alpha.15",
"@react-navigation/core": "^5.0.0-alpha.17",
"@react-navigation/native": "^5.0.0-alpha.13",
"@react-navigation/stack": "^5.0.0-alpha.29",
"expo": "^35.0.0",
"react": "16.8.3",
"react-dom": "16.8.3",
"react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
"react-native-gesture-handler": "~1.3.0",
"react-native-reanimated": "~1.2.0",
"react-native-safe-area-context": "~0.3.6",
"react-native-screens": "~1.0.0-alpha.23",
"react-native-web": "^0.11.7"
```
**Other**
node: `v10.13.0`
yarn: `1.19.1`

### Related issues
- https://github.com/react-navigation/react-navigation/issues/1464
- https://github.com/react-navigation/tabs/issues/16
- https://github.com/callstack/react-native-paper/pull/680

**Comment by ioness** [comment]
Hello!

With react-navigation 4.x bottomTabBar I did not have this problem

Now that I am migrating to 5.x I do. 

keyboardHidesTabBar hides the bottomTabs but when you press the back button you can still see the bug, bottomTab going back to its place.

This is kind of a compromise because usually those bottomTabs are used as the main navigator..

( I am using expo too ).

If I find a workaround I will write here.

**Comment by ioness** [comment]
After trying different things I realized it's not react-navigation but something else ( Probably react-native ) which I also did update...

With these RN changes maybe Expo should consider exposing android:windowSoftInputMode.

As for me: with material-bottom-tabs still moves the screen ( but less than bottom-tabs ) so I will play a little more until giving up :P.

Thanks a lot, if I find out something I will post again.

**Comment by ioness** [comment]
Already found a "workaround" that works for me.

Problem ( Only on Android )

My App has bottomTab navigation, when you press Contact Us you are directed to another screen where the keyboard opens. When you go back, you encounter the bottomTab icons in the middle of the screen for a fraction of a second.

If you use material-bottom-tabs, instead of encountering icons in the middle of the screen, part of my view is moved from bottom to top which is also a problem.

Workaround ( Only on Android ):

When the user press the back buttom:
1) Show loading animation
2) Dismiss the keyboard
3) Wait 200ms then goBack.

Anyway, I know this issue is closed but I wanted to share.

Cheers and keep up the good work with this more than amazing navigator..

Open source developers are our heroes!

**Comment by hadnet** [comment]
> The `keyboardHidesTabBar` option changes bottom margin on keyboard show/hide, so content will jump if the content isn't anchored to start of the screen. You can prevent the jump by passing `style: { position: 'absolute' }` to the `tabBarOptions`.

Thanks, man! style: { position: 'absolute' } solved the bottom margin changes on keyboard show/hide. Interestingly on iOS this isn't an issue, it happens on Android only.

**Comment by cklinx** [comment]
Any news? Same problem here

**Comment by ioness** [comment]
> Any news? Same problem here

My workaround is to use materialBottomTabBar and avoid flex in some screens

**Comment by cklinx** [comment]
@ioness Thanks, i mean if you can hide your tabbar. I cant =/ 
If i use a standard tabbar `tabBarOptions={{keyboardHidesTabBar: true}}` works fine but not with the custom one.
`tabBar={props => <MyTabBar {...props} />}`

**Comment by sagarv1997** [comment]
> @ioness Thanks, i mean if you can hide your tabbar. I cant =/
> If i use a standard tabbar `tabBarOptions={{keyboardHidesTabBar: true}}` works fine but not with the custom one.
> `tabBar={props => <MyTabBar {...props} />}`

I tried using this in custom one and it works, but like keyboardHidesTabBar option, there is also some delay in hiding the TabBar

function CustomNavigator(props) {
  const [showTab, setShowTab] = useState(true);

  useEffect(() => {
    Keyboard.addListener('keyboardDidShow', _keyboardDidShow);
    Keyboard.addListener('keyboardDidHide', _keyboardDidHide);

    return () => {
      Keyboard.removeListener('keyboardDidShow', _keyboardDidShow);
      Keyboard.removeListener('keyboardDidHide', _keyboardDidHide);
    };
  }, []);

  const _keyboardDidShow = () => {
    setShowTab(false);
  };

  const _keyboardDidHide = () => {
    setShowTab(true);
  };

  const {downloadProgress} = props;
  return (
    <View>
      {showTab && (
        <View>
          <BottomTabBar {...props} />
        </View>
      )}
    </View>
  );
}

**Comment by blazejczyk** [comment]
@sagarv1997 I would think about changing your solution into conditional displaying (instead of conditional rendering of null / tab bar). For example:

```
return (
  <View style={{display: showTab ? 'flex' : 'none'}}>
    <BottomTabBar {...props}/>
  </View>
);
```

I'm not sure if it's gonna fix the delay but I think it's worth trying.

**Comment by vshjxyz** [comment]
Hello, I've tried most of these solutions and listening to keyboard events https://github.com/react-navigation/react-navigation/issues/6928#issuecomment-614614678 worked with an animated bar. 

Going a bit deeper I realized nothing about this is needed if you keep the same behavior as iOs (making the keyboard act like it's in a position "absolute"). To so so you can simply change an attribute in your `AndroidManifest.xml` and set `android:windowSoftInputMode="adjustPan"` instead of `adjustResize` - this fixed it for me without the need to add any code

**Comment by MorenoMdz** [comment]
> AndroidManifest.xml

Thank you for the suggestion, do you have an idea of how it should be done when using Expo? As we don't access the `AndroidManifest.xml` file. 

Also, this could be an option to have in the tabBarOptions config.

**Comment by nhuesmann** [comment]
> > AndroidManifest.xml
> 
> Thank you for the suggestion, do you have an idea of how it should be done when using Expo? As we don't access the `AndroidManifest.xml` file.
> 
> Also, this could be an option to have in the tabBarOptions config.

Hey there, in Expo 38 you can configure this via `app.json`:

```
"android": {
  "softwareKeyboardLayoutMode": "pan"
},
```

Here's the reference to that part in the docs: https://docs.expo.io/versions/latest/config/app/

**Comment by brimby** [comment]
Oh wow I've gone through so many threads trying everything suggested. @nhuesmann has the answer for Expo users. Thanks a bunch.

**Comment by tranvanduong2483** [comment]
1. android:windowSoftInputMode="stateAlwaysHidden|adjustPan"
2. uninstall app and built it again!

Work for me! <3

**Comment by theowhat** [comment]
> Hello, I've tried most of these solutions and listening to keyboard events [#6928 (comment)](https://github.com/react-navigation/react-navigation/issues/6928#issuecomment-614614678) worked with an animated bar.
> 
> Going a bit deeper I realized nothing about this is needed if you keep the same behavior as iOs (making the keyboard act like it's in a position "absolute"). To so so you can simply change an attribute in your `AndroidManifest.xml` and set `android:windowSoftInputMode="adjustPan"` instead of `adjustResize` - this fixed it for me without the need to add any code

Hey! I am using expo and I am on SDK 36, do you know another solution? I have this error message when I build the app: 
```
Error: Problem validating fields in app.json. See https://docs.expo.io/workflow/configuration/
 • Field: android - should NOT have additional property 'softwareKeyboardLayoutMode'.
Couldn't publish because errors were found. (See logs above.) Please fix the errors and try again.
```

Thank you for your help !

**Comment by MWaqasHussain-dev** [comment]
@nhuesmann  many thanks

**Comment by NishargShah** [comment]
Sometime setting `android:windowSoftInputMode` to `adjustPan` or `adjustResize` is not ideal idea because it effects whole application.

so that is my idea to solve that error.

###  React Navigation 5

```
import React, { useEffect, useState } from 'react';
import { Platform, Keyboard } from 'react-native';
import { BottomTabBar } from '@react-navigation/bottom-tabs';

const CustomBottomTabBar = props => {
  const [visible, setVisible] = useState(true);

  useEffect(() => {
    let keyboardEventListeners;
    if (Platform.OS === 'android') {
      keyboardEventListeners = [
        Keyboard.addListener('keyboardDidShow', () => setVisible(false)),
        Keyboard.addListener('keyboardDidHide', () => setVisible(true)),
      ];
    }
    return () => {
      if (Platform.OS === 'android') {
        keyboardEventListeners &&
          keyboardEventListeners.forEach(eventListener => eventListener.remove());
      }
    };
  }, []);

  const render = () => {
    if (Platform.OS === 'ios') {
      return <BottomTabBar {...props} />;
    }
    if (!visible) return null;
    return <BottomTabBar {...props} />;
  };

  return render();
};

export default CustomBottomTabBar;

```

**Comment by manithin** [comment]
"keyboardHidesTabBar" param in Tab Navigator tabBarOptions hides tab buttons behind the keyboard.

 <Tab.Navigator
      tabBarOptions={{
        keyboardHidesTabBar: true,
      }}>
 ....
    </Tab.Navigator>

**Comment by IlmirD** [comment]
android:windowSoftInputMode="adjustPan|adjustResize">
worked for me

**Comment by dave-vazquez** [comment]
omg thank you! @nhuesmann

**Comment by Mazelos** [comment]
> > @ioness Thanks, i mean if you can hide your tabbar. I cant =/
> > If i use a standard tabbar `tabBarOptions={{keyboardHidesTabBar: true}}` works fine but not with the custom one.
> > `tabBar={props => <MyTabBar {...props} />}`
> 
> I tried using this in custom one and it works, but like keyboardHidesTabBar option, there is also some delay in hiding the TabBar
> 
> ```
> function CustomNavigator(props) {
>   const [showTab, setShowTab] = useState(true);
> 
>   useEffect(() => {
>     Keyboard.addListener('keyboardDidShow', _keyboardDidShow);
>     Keyboard.addListener('keyboardDidHide', _keyboardDidHide);
> 
>     return () => {
>       Keyboard.removeListener('keyboardDidShow', _keyboardDidShow);
>       Keyboard.removeListener('keyboardDidHide', _keyboardDidHide);
>     };
>   }, []);
> 
>   const _keyboardDidShow = () => {
>     setShowTab(false);
>   };
> 
>   const _keyboardDidHide = () => {
>     setShowTab(true);
>   };
> 
>   const {downloadProgress} = props;
>   return (
>     <View>
>       {showTab && (
>         <View>
>           <BottomTabBar {...props} />
>         </View>
>       )}
>     </View>
>   );
> }
> ```

Thanks, nice solution. Like you say there's a little delay but you have at the same time the benefits of `android:windowSoftInputMode` set to  `adjustResize ` (that is perfect for inputs) and the tab disappear when needed.

**Comment by daviddossantos** [comment]
thanks @nhuesmann  :)

**Comment by ravdsn** [comment]
> 
> 
> > > AndroidManifest.xml
> > 
> > 
> > Thank you for the suggestion, do you have an idea of how it should be done when using Expo? As we don't access the `AndroidManifest.xml` file.
> > Also, this could be an option to have in the tabBarOptions config.
> 
> Hey there, in Expo 38 you can configure this via `app.json`:
> 
> ```
> "android": {
>   "softwareKeyboardLayoutMode": "pan"
> },
> ```
> 
> Here's the reference to that part in the docs: https://docs.expo.io/versions/latest/config/app/

thanks @nhuesmann, it worked

**Comment by tylorr** [comment]
> `keyboardHidesTabBar: true` isn't ideal but it's the best we can do right now with what is exposed by react-native's keyboard api, which if i understand correctly is limited by the related android apis. it seems that we can't know that the keyboard will appear before it does, and so we have to animate after the keyboard is already visible.

Is there anyway to turn the animation off for Android? Maybe some flag to disable the animation. I'd rather the tab bar disappear immediately just like the keyboard shows immediately.

**Comment by Marvin3Benz** [comment]
> > `keyboardHidesTabBar: true` isn't ideal but it's the best we can do right now with what is exposed by react-native's keyboard api, which if i understand correctly is limited by the related android apis. it seems that we can't know that the keyboard will appear before it does, and so we have to animate after the keyboard is already visible.
> 
> Is there anyway to turn the animation off for Android? Maybe some flag to disable the animation. I'd rather the tab bar disappear immediately just like the keyboard shows immediately.

As @nhuesmann  mentioned before, add
`"android": {
  "softwareKeyboardLayoutMode": "pan"
},`
in your app.json worked for me. I tested when the TextInput component get focused, the bottom tab bar disappears immediately. Without above code, there would be an animation.
Again, thanks @nhuesmann .

**Comment by tylorr** [comment]
> > > `keyboardHidesTabBar: true` isn't ideal but it's the best we can do right now with what is exposed by react-native's keyboard api, which if i understand correctly is limited by the related android apis. it seems that we can't know that the keyboard will appear before it does, and so we have to animate after the keyboard is already visible.
> > 
> > 
> > Is there anyway to turn the animation off for Android? Maybe some flag to disable the animation. I'd rather the tab bar disappear immediately just like the keyboard shows immediately.
> 
> As @nhuesmann mentioned before, add
> `"android": { "softwareKeyboardLayoutMode": "pan" },`
> in your app.json worked for me. I tested when the TextInput component get focused, the bottom tab bar disappears immediately. Without above code, there would be an animation.
> Again, thanks @nhuesmann .

I'm not using expo so this doesn't work for me

**Comment by Marvin3Benz** [comment]
> > > > `keyboardHidesTabBar: true` isn't ideal but it's the best we can do right now with what is exposed by react-native's keyboard api, which if i understand correctly is limited by the related android apis. it seems that we can't know that the keyboard will appear before it does, and so we have to animate after the keyboard is already visible.
> > > 
> > > 
> > > Is there anyway to turn the animation off for Android? Maybe some flag to disable the animation. I'd rather the tab bar disappear immediately just like the keyboard shows immediately.
> > 
> > 
> > As @nhuesmann mentioned before, add
> > `"android": { "softwareKeyboardLayoutMode": "pan" },`
> > in your app.json worked for me. I tested when the TextInput component get focused, the bottom tab bar disappears immediately. Without above code, there would be an animation.
> > Again, thanks @nhuesmann .
> 
> I'm not using expo so this doesn't work for me

Did you research on `android:windowSoftInputMode` ? I think that is probably a good point to get in. Since in Expo it was mapped to `softwareKeyboardLayoutMode`. Hope that would help u.

**Comment by tylorr** [comment]
> > > > > `keyboardHidesTabBar: true` isn't ideal but it's the best we can do right now with what is exposed by react-native's keyboard api, which if i understand correctly is limited by the related android apis. it seems that we can't know that the keyboard will appear before it does, and so we have to animate after the keyboard is already visible.
> > > > 
> > > > 
> > > > Is there anyway to turn the animation off for Android? Maybe some flag to disable the animation. I'd rather the tab bar disappear immediately just like the keyboard shows immediately.
> > > 
> > > 
> > > As @nhuesmann mentioned before, add
> > > `"android": { "softwareKeyboardLayoutMode": "pan" },`
> > > in your app.json worked for me. I tested when the TextInput component get focused, the bottom tab bar disappears immediately. Without above code, there would be an animation.
> > > Again, thanks @nhuesmann .
> > 
> > 
> > I'm not using expo so this doesn't work for me
> 
> Did you research on `android:windowSoftInputMode` ? I think that is probably a good point to get in. Since in Expo it was mapped to `softwareKeyboardLayoutMode`. Hope that would help u.

Oh right, yeah switching to `adjustPan` for `android:windowSoftInputMode` is not an option, too many consequences for changing that mode. A flag to disable the animation seems like a much more direct and simpler solution.

**Comment by scottwio** [comment]
If like me you don't want to move to `adjustPan` because it has other knock-on effects. Hiding the tabbar can be achieved by position the tabbar off screen whenever the keyboard is visible. `keyboardHidesTabBar` is the other option but you end up with an animation that doesn't look so great. Below is a hook to hide the tab bar on Android when keyboard is visible hopefully one day there will be a better solution and this can be deleted.

```
const useHideTabBarOnKeyboardOpenAndroid = (tabBarSize: number) => {
  const [TabBarStyle, setTabBarStyle] = useState<ViewStyle | null>(null);

  const keyboardDidShow = useCallback(() => {
    setTabBarStyle({
      bottom: -tabBarSize,
      position: "absolute"
    });
  }, [tabBarSize]);

  const keyboardDidHide = useCallback(() => {
    setTabBarStyle(null);
  }, []);

  useEffect(() => {
    if (Platform.OS === "android") {
      Keyboard.addListener("keyboardDidShow", keyboardDidShow);
      Keyboard.addListener("keyboardDidHide", keyboardDidHide);

      return () => {
        Keyboard.removeListener("keyboardDidShow", keyboardDidShow);
        Keyboard.removeListener("keyboardDidHide", keyboardDidHide);
      };
    }
  }, [keyboardDidHide, keyboardDidShow]);
  return TabBarStyle;
};

const TabBar = () => {

 const hideAndroidStyle = useHideTabBarOnKeyboardOpenAndroid(200);

  return <Tab.Navigator
      tabBarOptions={{
        style: [hideAndroidStyle]
      }}
    >


```

**Comment by armenavanesi** [comment]
+1 on not wanting to see the animation of the tabbar closing when using `keyboardHidesTabBar` + `softwareKeyboardLayoutMode`

**Comment by ivomofor** [comment]
Thanks a lot to you @nhuesmann I am new to react native and i am using expo and i faced this same issue and adding tabBarOptions={{
        keyboardHidesTabBar: false,
      }}
did fix the issue but it had a few delay to hide the tap bar so adding this code to app.json bellow worked fine for me
"android": {
      "softwareKeyboardLayoutMode": "pan",
      } 

i am using "expo": "^41.0.1", :)

Thanks a lot @nhuesmann

**Comment by dayze** [comment]
Another solution if you don't want to change the ``windowSoftInputMode`` for your entire project is to programmatically change the inputMode to pan/adjust whenever you want 

This library [https://github.com/MR03web/react-native-set-soft-input-mode](url) allow you to do that but it doesn't seems to be maintained anymore.
You can also just create a native component project if you don't already have one, for example in kotlin: 

```
  @ReactMethod
  fun setLayoutToAdjustPan() {
    val activity = getCurrentActivity();
    activity?.runOnUiThread(Runnable {
      activity.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN);
    })
  }

  @ReactMethod
  fun setLayoutToAdjustResize() {
    val activity = getCurrentActivity();
    activity?.runOnUiThread(Runnable {
      activity.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
    })
  }
```

**Comment by mateus-azevedo** [comment]
I've solved this problem using the screenOptions attribute

Following the example below:

`<Tab.Navigator screenOptions={{tabBarHideOnKeyboard: true}}>`

Similar result to [AndroidManifest.xml](https://github.com/react-navigation/react-navigation/issues/6700#issuecomment-634084564)

My `package.json`:

```
"@react-native-community/masked-view": "^0.1.11",
"@react-navigation/bottom-tabs": "^6.0.9",
"@react-navigation/drawer": "^5.12.5",
"@react-navigation/native": "^5.9.4",
"@react-navigation/stack": "^5.14.5",
```

**Comment by HumbleKingDev** [comment]
in app.json under android just add: 
**"softwareKeyboardLayoutMode": "pan"**

**Comment by Nivethan-Ar** [comment]
I'm using react navigation V6 since i'm using a custom tabBar the `tabBarHideOnKeyboard: true` prop not working but when i change the custom tabBar to default tab bar that prop works but i don't like the behavior  of that prop on android, so i used keyboard from react-native to check if the keyboard is active or not and setting the css display prop to 'none'
`
  const [keyboardStatus, setKeyboardStatus] = useState<boolean>();

  useEffect(() => {
    const showSubscription = Keyboard.addListener('keyboardDidShow', () => {
      setKeyboardStatus(true);
    });
    const hideSubscription = Keyboard.addListener('keyboardDidHide', () => {
      setKeyboardStatus(false);
    });

    return () => {
      showSubscription.remove();
      hideSubscription.remove();
    };
  }, []);

`
so on the custom tab bar component now i can do like this.
`
    <View style={
      [
        styles.mainContainer,
        keyboardStatus ? styles.hideTabNavigation : null,
      ]
    }
    >
` 
hope this will help someone until they fix this issue!

**Comment by abielg** [comment]
> in app.json under android just add: **"softwareKeyboardLayoutMode": "pan"**

This worked for me! Thanks :)

**Comment by Uzef1997** [comment]
I was running into same issue and found one solution setting tabBarHideOnKeyboard to true is not the only thing we have to change windowSoftInputMode to "adjustPan" from adjustResize, adjustResize will resize your whole component and that will cause animation issue with tabbar. I have changed this option to adjustPan.
adjustPan will shift the whole page up to make room for the keyboard,
We can set this option inside our AndroidManifest.xml file 
`android:windowSoftInputMode="adjustResize"`

**Comment by Jansen-Stanlie** [comment]
> Sometime setting `android:windowSoftInputMode` to `adjustPan` or `adjustResize` is not ideal idea because it effects whole application.
> 
> so that is my idea to solve that error.
> 
> ### React Navigation 5
> **BottomTabBar.js**
> 
> ```
> import React, { useEffect, useState } from 'react';
> import { Platform, Keyboard } from 'react-native';
> import { BottomTabBar } from '@react-navigation/bottom-tabs';
> 
> const CustomBottomTabBar = props => {
>   const [visible, setVisible] = useState(true);
> 
>   useEffect(() => {
>     let keyboardEventListeners;
>     if (Platform.OS === 'android') {
>       keyboardEventListeners = [
>         Keyboard.addListener('keyboardDidShow', () => setVisible(false)),
>         Keyboard.addListener('keyboardDidHide', () => setVisible(true)),
>       ];
>     }
>     return () => {
>       if (Platform.OS === 'android') {
>         keyboardEventListeners &&
>           keyboardEventListeners.forEach(eventListener => eventListener.remove());
>       }
>     };
>   }, []);
> 
>   const render = () => {
>     if (Platform.OS === 'ios') {
>       return <BottomTabBar {...props} />;
>     }
>     if (!visible) return null;
>     return <BottomTabBar {...props} />;
>   };
> 
>   return render();
> };
> 
> export default CustomBottomTabBar;
> ```
> 
> **AppNavigator.js**
> 
> ```
> import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
> 
> const bottomTabNavigator = createBottomTabNavigator();
> 
> <BottomNavigator
>     screenOptions={bottomTabScreenOptions}
>     tabBarOptions={bottomTabBarOptions}
>     tabBar={props => <CustomBottomTabBar {...props} />}
> >
>     ......
> </BottomNavigator>
> ```

this man is savior, god bless you

**Comment by khadijatuzzehra** [comment]
Inside screenOptions use "tabBarHideOnKeyboard: true". Works for me!

**Comment by symonxdd** [comment]
Setting `tabBarHideOnKeyboard` to true under the android section in `app.json` does work and is most likely the preferred way to handle this issue; though I didn't see any result until I **reloaded** the app...!

I'm using Expo, so I issued the reload or (r) command in the CLI where the dev server is running 🙏

**Comment by rchalaaa** [comment]
Guys I just found the solution for this! Just add "softwareKeyboardLayoutMode": "pan" in the app.json settings if you're working with expo. Thank me later 😉

```
"android": {
      "buildNumber": "1.0.0",
      "adaptiveIcon": {
        "foregroundImage": "./assets/icons/adaptive-icon.png",
        "monochromeImage": "./assets/icons/adaptive-icon.png",
        "backgroundColor": "#bc2078"
      },
      "package": "com.nexxclub.nexxclubs",
      "softwareKeyboardLayoutMode": "pan"
    },
```
