### ISSUE TITLE
Usage with Redux-Persist causes state to be overwritten

### ISSUE THREAD

**Issue by nextriot** [react-navigation/react-navigation-4#6703]
### Current Behavior

Using in combination with Redux-Persist, upon app being reloaded Redux-Persist's actions are fired, but then reloaded and any persisted state is overwritten. When I remove React Navigation the code acts as expected.

### Expected Behavior

The state should be persisted and the app should not be loaded twice.

### How to reproduce

Here is a link to a repo I created with the minimum required code to reproduce the error: https://expo.io/@kanguru/rn-nav-redux-persist
And here is the Githu repo for the project: https://github.com/nextriot/React-Navigation-5-Redux-Persist

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 
| @react-navigation/core | ^5.0.0-alpha.17
| @react-navigation/native | ^5.0.0-alpha.13
| @react-navigation/stack | ^5.0.0-alpha.29
| react-native     | 0.59.8
| expo             | 35.0.0
| node             | 10.16.0
| npm or yarn      | 1.10.1

**Comment by dancomanlive** [comment]
Please add https://github.com/react-navigation/react-navigation/issues/6703#issuecomment-545183468 this comment to the docs. I figured that the state was not lost but did not understand why the remote debugger was switching back and forth between redux and react-navigation's state.  "Autoselect instances" was the answer I was looking for :)
