### ISSUE TITLE
useScrollToTop and Scrollables question.

### ISSUE THREAD

**Issue by immortalx** [react-navigation/react-navigation-4#6712]
I'm trying this new version and i'm a little confused about useScrollToTop and the old wrapped FlatList/Scrollview components.

If i got it right, we won't import FlatList/ScrollView from the navigation anymore and to wire useScrollToTop, we just need to add it to the initialScreen of the Stack and the TabBar will listen and fire a scroll to top. Is that correct?

I tried this way and it didn't work, my screen is inside a Stack and I'm using a TabNavigator, i also got a warning about the ref on my screen: "function components cannot be given refs".

Am i missing something here?
Thank you!

**Comment by petermirmo** [comment]
It does not work in the latest version with nested navigations

**Comment by KresimirJurkovic** [comment]
Yep, same here, cannot get it to work

**Comment by DomVinyard** [comment]
I would also love for it to work with nested navigations

**Comment by kot-ezhva** [comment]
> `useScrollToTop` still isn't working with nested navigators as of `v6.1.9`. You can clone a [simple example here](https://github.com/basememara/expo-nav-demo).
> 
> It seems to scroll to the top of the nearest header even tho that header has `headerShown: false`, or I think it might not be considering the safe areas.
> 
> ![Simulator Screen Recording - iPhone 15 Pro - 2024-01-29 at 16 54 42](https://github.com/react-navigation/react-navigation/assets/892152/fb818eb3-6347-402f-963a-9eeb2f121223) [ ![Simulator Screen Recording - iPhone 15 Pro - 2024-01-29 at 16 54 42](https://github.com/react-navigation/react-navigation/assets/892152/fb818eb3-6347-402f-963a-9eeb2f121223) ](https://private-user-images.githubusercontent.com/892152/300463984-fb818eb3-6347-402f-963a-9eeb2f121223.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMzU2NzAsIm5iZiI6MTczNTIzNTM3MCwicGF0aCI6Ii84OTIxNTIvMzAwNDYzOTg0LWZiODE4ZWIzLTYzNDctNDAyZi05NjNhLTllZWIyZjEyMTIyMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQxNzQ5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2I2YWYzYjBjMWRkZGZkOWNmY2MzZDAxZmViZmNhNjZhOWJmN2EzMDE5YzhkZWJhZTEwNzJjNDVmMTRkZDZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-k4Nj-JfYwixJbS5wgwLmKhKsc5AG1yrrTurUw2Wngo) [ ](https://private-user-images.githubusercontent.com/892152/300463984-fb818eb3-6347-402f-963a-9eeb2f121223.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMzU2NzAsIm5iZiI6MTczNTIzNTM3MCwicGF0aCI6Ii84OTIxNTIvMzAwNDYzOTg0LWZiODE4ZWIzLTYzNDctNDAyZi05NjNhLTllZWIyZjEyMTIyMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQxNzQ5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2I2YWYzYjBjMWRkZGZkOWNmY2MzZDAxZmViZmNhNjZhOWJmN2EzMDE5YzhkZWJhZTEwNzJjNDVmMTRkZDZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-k4Nj-JfYwixJbS5wgwLmKhKsc5AG1yrrTurUw2Wngo)

U have a fix for this?
