### ISSUE TITLE
Header is rendered behind Card is navigator mode is modal and headerTransparent is true

### ISSUE THREAD

**Issue by dulmandakh** [react-navigation/react-navigation-4#6717]
### Current Behavior

When I set Stack navigator mode to **modal**, and set **headerTransparent** to true on screen options, header is rendered behind the Card. Therefore, header is covered and invisible to user then hides navigation.

### Expected Behavior

User should be able to see header, thus navigation.

### How to reproduce

```javascript
const Stack = createStackNavigator();
<Stack.Navigator mode="modal">
  <Stack.Screen
    name="Modal"
    options={{headerTransparent: true}}
    component={() => <View style={{backgroundColor: '#0006', flex: 1}} />}
  />
</Stack.Navigator>
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 5.0.0-alpha.17 
| react-native     | 0.61.0-rc.3
| node             | v12.10.0
| npm or yarn      | v1.17.3

**Comment by MaximAbramchuck** [comment]
still having this issue
