### ISSUE TITLE
Custom contentComponent in Drawer re-render everytime

### ISSUE THREAD

**Issue by alexakasanjeev** [react-navigation/react-navigation-4#6718]
### Current Behavior

I have implemented a **Drawer** which host a **Stack** navigator inside. I am giving a custom component to be render in `contentComponent` in Drawer. But the custom component in Drawer keeps rendering after every:
1. Whenever the Drawer is open
2. Whenever the Drawer is close
3. Any screen is open in Stack Navigator

### Expected Behavior

- custom component given to Drawer should not keep re rendering every time any screen is open from the stack

### How to reproduce

1. run `git clone https://github.com/alexakasanjeev/magento_react_native.git && cd magento_react_native`
2. Change the branch to `git checkout feature/react-navigation`
3. install dependency `npm install`
4. In terminal type `npm start`
5. In another terminal run `react-native run-android`
6. Once the app is running in device, enable `Debug Js Remotely` from dev menu
7. Open the console of chrome and click on any button in the App
8. Every time any button is clicked to open new screen, the custom component keeps re-rendering as seen from console logs
>  Rendering Drawer Navigation!

#### Screenshots
![Screenshot from 2019-09-14 16-26-43](https://user-images.githubusercontent.com/13250741/64907156-8d32b200-d70c-11e9-98fc-be102aa36f67.png)

### Your Environment

| software         | version
| ---------------- | -------
| @react-navigation/core | ^5.0.0-alpha.8
| @react-navigation/native | ^5.0.0-alpha.7
| @react-navigation/drawer | ^5.0.0-alpha.8
| @react-navigation/stack | ^5.0.0-alpha.15
| react-native     | 0.60.4
| node             | v10.15.3
| yarn      | 1.17.3

**Comment by kapilbhosale** [comment]
I was also facing the same issue, here is how I managed to solve mine. 
Hope this will help you.

logic: check if the drawer is open or close, return without doing heavy stuff if the drawer is closed.

```
  import {useIsDrawerOpen} from '@react-navigation/drawer';
  ..
  ..
  const isDrawerOpen = useIsDrawerOpen();
  if (!isDrawerOpen) {
    return(<></>)
  }
```

**Comment by BlazeGawlik** [comment]
I see you are using react-navigation 5, the umountOnBlur option worked great for me: https://stackoverflow.com/a/62675176/5970652
